<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Editar Cadastro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

    <!--header start here-->
    <div class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <nav class="menu_logado">
                <ul class="menu">
                    <li class="item"><a href="/index_projeto">Projetos</a></li>
                </ul>
            </nav>
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
                            <div class="user-name">
                                <?php session_start(); ?>
                                <p><?php echo $_SESSION['nome']; ?></p>                                
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>


    <div class="application_container container-fluid">
        <div class='row'>
            <div class='col-lg-4 col-md-4 mg_bot_20'>
                <div class='box'>
                    <ul>
                        <li>
                            <a class="block mg_bot_20" href="/cadastro_editar">Informações básicas</a>
                        </li>
                        <li>
                            <a class="block mg_bot_20" href="/editar_senha">Alterar Senha</a>
                        </li>
                        <li>
                            <a class="block mg_bot_20" href="#">Excluir conta</a>
                        </li>
                        <li>
                            <a class="block" href="/politica_privacidade">Termos de Privacidade</a>
                        </li>
                    </ul>
                </div>

            </div>

            <div class="col-lg-8 col-md-8 mg_bot_20">
                <form class="box" id="edit_user" action="cadastro_editar" method="Post">
                    <h1>Informações Pessoais</h1>
                    <div class='box_content'>

                        <div class="form_group">
                            <label for="user_first_name">Nome Completo</label>
                            <input class="form_input" type="text" value="Adriana Diniz" name="user[first_name]" id="user_first_name" />
                        </div>

                        <div class='form_group'>
                            <label for="user_email">Email</label>
                            <input class="form_input" type="email" value="dri.ragazoni@gmail.com" name="user[email]" id="user_email" />

                        </div>
                        <div class='row'>
                            <div class='form-group col-md-6 col-lg-6 col-sm-6'>
                                <label for="user_gender">Selecionar Gênero</label>
                                <select class="form_input" name="user_gender" id="user_gender">
                                    <option value="">Selecionar</option>
                                    <option selected="selected" value="F">Feminino</option>
                                    <option value="M">Masculino</option>
                                    <option value="N">Neutro</option>
                                </select>

                            </div>
                            <div class="form-group col-md-6 col-lg-6 col-sm-6">
                                <label class="block" for="user_birthday">Data de aniversário</label>
                                <input type="date" name="bday" class="form_input form_date">

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="label_lg" for="user_places_attributes_nationality">Estado onde mora:</label>
                            <select class="form_input input_lg" name="user[places_attributes][nationality]" id="user_places_attributes_nationality">
                                <option value="">Selecionar...</option>
                                <option value="AC">Acre</option>
                                <option value="AL">Alagoas</option>
                                <option value="AP">Amapá</option>
                                <option value="AM">Amazonas</option>
                                <option value="BA">Bahia</option>
                                <option value="CE">Ceará</option>
                                <option value="DF">Distrito Federal</option>
                                <option value="ES">Espírito Santo</option>
                                <option value="GO">Goiás</option>
                                <option value="MA">Maranhão</option>
                                <option value="MT">Mato Grosso</option>
                                <option value="MS">Mato Grosso do Sul</option>
                                <option value="MG">Minas Gerais</option>
                                <option value="PA">Pará</option>
                                <option value="PB">Paraíba</option>
                                <option value="PR">Paraná</option>
                                <option value="PE">Pernambuco</option>
                                <option value="PI">Piauí</option>
                                <option value="RJ">Rio de Janeiro</option>
                                <option value="RN">Rio Grande do Norte</option>
                                <option value="RS">Rio Grande do Sul</option>
                                <option value="RO">Rondônia</option>
                                <option value="RR">Roraima</option>
                                <option value="SC">Santa Catarina</option>
                                <option value="SP">São Paulo</option>
                                <option value="SE">Sergipe</option>
                                <option value="TO">Tocantins</option>
                                <option value="ES">Estrangeiro</option>
                            </select>
                        </div>

                    </div>


                    <div class="box_actions">
                        <button name="button" type="submit" class="btn btn_lg btn_primary">Alterar</button>
                    </div>
                </form>
            </div>
        </div>





</body>

</html>