<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Alterar Senhas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <nav class="menu_logado">
                <ul class="menu">
                    <li class="item"><a href="/index_projeto">Projetos</a></li>
                </ul>
            </nav>
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
                            <div class="user-name">
                                <?php session_start();?>
                                <p><?php echo $_SESSION['nome']; ?></p>                             
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
    <div class='application_container container-fluid'>
        <div class='row'>
            <div class='col-lg-4 col-md-4 mg_bot_20'>
                <div class='box'>
                    <ul>
                        <li>
                            <a class="block mg_bot_20" href="/cadastro_editar">Informações básicas</a>
                        </li>
                        <li>
                            <a class="block mg_bot_20" href="/editar_senha">Alterar Senha</a>
                        </li>
                        <li>
                            <a class="block mg_bot_20" href="/excluir_conta">Excluir conta</a>
                        </li>
                        <li>
                            <a class="block" href="/politica_privacidade">Termos de Privacidade</a>
                        </li>
                    </ul>
                </div>

            </div>


            <div class="col-lg-8 col-md-8 mg_bot_20">

                <form class="box new_user" id="new_user" action="#" method="POST">
                    <h1>Alterar Senha</h1>
                    <div class="box_content">
                        <div class="form-group">
                            <input autocomplete="off" type="password" class="form_input password_input" value="" id="pwd_atual" placeholder="Senha atual" name="senha" required>
                        </div>
                        <div class="form-group">
                            <input autocomplete="off" type="password" class="form_input password_input" value="" id="pwd_nova" placeholder="Nova senha" name="senha" required>
                        </div>
                        <div class="form-group">
                            <input autocomplete="off" type="password" class="form_input password_input" value="" id="pwd_confirmacao" placeholder="Confirmar senha" name="senha" required>
                        </div>
                    </div>

                    <div class="box_actions">
                        <button name="button" type="submit" class="btn btn_lg btn_primary">Alterar</button>
                    </div>

                </form>

            </div>
        </div>



</body>

</html>