<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Alterar Senhas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="index.html" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/in4.jpg" alt=""> </span>
                            <div class="user-name">
                                <p>Anna Barbara</p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="cadastro_editar.html"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="#"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="#"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
    <section class="registration">
        <div class="container-fluid">
            <div class="box registration_box">
                <h1 class="border_bottom h2 text_center">Alterar Senha</h1>
                <form class="new_user" id="new_user" action="#" method="POST">
                    <div class="form_group">
                        <input autocomplete="off" type="password" class="form_input password_input" value="" id="pwd_atual" placeholder="Senha atual" name="senha" required>
                    </div>
                    <div class="form_group">
                        <input autocomplete="off" type="password" class="form_input password_input" value="" id="pwd_nova" placeholder="Nova senha" name="senha" required>
                    </div>
                    <div class="form_group">
                        <input autocomplete="off" type="password" class="form_input password_input" value="" id="pwd_confirmacao" placeholder="Confirmar senha" name="senha" required>
                    </div>

                    <input type="submit" value="Alterar" class="btn btn_lg btn_primary btn_block" />
            </div>
            </form>
        </div>

    </section>
   
</body>

</html>