<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>excluir Conta</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="index.html" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
                            <div class="user-name">
                                <?php session_start();?>
                                <p><?php echo $_SESSION['nome'];?></p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
    <div class='application_container container-fluid'>
        <div class='row'>
            <div class='col-lg-4 col-md-4 mg_bot_20'>
                <div class='box'>
                    <ul>
                        <li>
                            <a class="block mg_bot_20" href="/cadastro_editar">Informações básicas</a>
                        </li>
                        <li>
                            <a class="block mg_bot_20" href="/editar_senha">Alterar Senha</a>
                        </li>
                        <li>
                            <a class="block mg_bot_20" href="/excluir_conta">Excluir conta</a>
                        </li>
                        <li>
                            <a class="block" href="/politica_privacidade">Termos de Privacidade</a>
                        </li>
                    </ul>
                </div>

            </div>


            <div class="col-lg-8 col-md-8 mg_bot_20">

                <form class="box new_user" id="new_user" action="#" method="POST">
                    <h1>Excluir Conta</h1>
                    <p class='mg_bot_20'>A partir do momento que você apagar sua conta:</p>
                    <ul class='restrict-account-box'>
                        <li class='mg_bot_20'>
                            <i class='icon icon-check-simple'></i>
                            <p>Vamos verificar sua identidade para fins de segurança antes de aceitar o pedido de exclusão. Ou seja, para promover uma comunidade segura e sem abusos, não permitimos que usuários que tenham cometido infrações claras possam simplesmente remover a conta.</p>
                        </li>
                        <li class='mg_bot_20'>
                            <i class='icon icon-check-simple'></i>
                            <p>Você não pode mais recuperar, reativar ou reassociar suas informações.</p>
                        </li>
                        <li class='mg_bot_30'>
                            <i class='icon icon-check-simple'></i>
                            <p>Nós desidentificamos e desassociamos seus dados a sua conta, ou seja, fazemos com que suas informações não estejam associados a você de nenhuma maneira. Guardamos esses dados anônimos para continuamente melhorar a experiência dos nossos serviços através de pesquisas e análises.</p>
                        </li>
                    </ul>
                    <div class='box_actions'>
                        <a class="btn btn_danger btn_lg" data-toggle="modal" data-target="#delete-modal" href="#">Excluir conta</a>
                    </div>
            </div>
            
        </div>
    </div>


    </form>

    </div>
    </div>



</body>

</html>