<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Experiências</title>
</head>

<body>
    <a href="/logoff"></a>
    <!--Menu usuário logado-->
    <div class="header-main">
        <a href="/index" class="logo"><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <nav class="menu_logado">
                <ul class="menu">
                    <li class="item"><a href="/home_projetos">Projetos</a></li>
                </ul>
            </nav>
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>

        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
                            <div class="user-name">
                                <?php session_start(); ?>
                                <p><?php echo $_SESSION['nome']; ?></p>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>


    <div class="application_container container-fluid">
        <div class='row'>
            <div class="col-md-8 col-lg-8 col-sm-10 col-md-offset-2 col-lg-offset-2 col-sm-offset-1">
                <form class="box" id="user_profile" action="#" method="post">
                    <h1 class="mg_bot_40 text_center">Experiências</h1>
                    <p class='big mg_bot_20'>Hora de se abrir e nos contar um pouco mais das suas experiências de vida.</p>

                    <div class='form-group'>
                        <label class="label_lg" for="user_education">Educação</label>
                        <div class="form-group">
                            <textarea class="form-control" rows="5" name="education" id="user_education" placeholder="Escreva aqui sobre seus estudos, cursos"></textarea>
                        </div>

                        <div class="form-group">
                            <label class="label_lg" for="user_work_experience">Experiências profissionais</label>
                           <textarea class="form-control" rows="5" name="user_work_experience" id="work_experience" placeholder="Nos conte um pouco sobre suas experiências profissionais"></textarea>
                        </div>
                        
                        <div class='box_actions'>
                            <input type="submit" name="commit" value="Salvar" class="btn btn_lg btn_primary">
                            <a class="btn btn_lg btn_secondary" href="/perfil">Cancelar</a>
                        </div>
                </form>
            </div>
        </div>
    </div>



</body>