<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Fotos</title>
    <meta charset="UTF-8" />
</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
                            <div class="user-name">
                                <?php session_start();?>
                                <p><?php echo $_SESSION['nome'];?></p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>

                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>

    <div class='application_container container-fluid'>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-10 form_photo">
                <form class="box registration_box" id="edit_user_photo" action="/fotos" method="post">
                    <h1 class='mg_bot_20'>Escolher foto</h1>
                    <div class='box_content'>
                        <div class='row'>
                            <div class='col-lg-5 col-md-5 col-sm-6 text_center'>
                                <div class='small-row'>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 1" />
                                    </div>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 2" />
                                    </div>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 3" />
                                    </div>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 4" />
                                    </div>
                                </div>
                            </div>
                            <div class='col-lg-7 col-md-7 col-sm-6'>
                                <h4>Sua foto vai causar a primeira impressão!!! </h4>
                                <p>Lembre-se de escolher uma que mostre seu rosto, <br>
                                    Evite fotos com bichinhos, paisagens ou em grupo.</p>
                            </div>
                        </div>
                    </div>
                    <div class='form-group'>
                        <input class="form_input" type="file" name="photo" id="user_photo" />
                    </div>
                    <div class='box_actions'>
                        <input type="submit" name="commit" value="Fazer upload" class="btn btn_lg btn_primary" data-disable-with="Uploadando..." id="upload_avatar" />
                    </div>
                </form>
            </div>
        </div>

    </div>
</body>

</html>