<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Habilidades</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
    <!--Menu usuário logado-->
    <div class="header-main">
        <a href="index.html" class="logo"><b>C</b>olabora</a>
        <div class="w3layouts-right">
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>

        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/in4.jpg" alt=""> </span>
                            <div class="user-name">
                                <p>Malorum</p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="clearfix"> </div>
    </div>

    <div class="application_container container-fluid">
        <form class="onboarding-preferences__form" id="new_user_preferences" action="/salvarHabilidade">
            <h1 class="text_center">Quais suas Habilidades</h1>
            <p class="huge text_center">Selecione somente até três opções</p>
            <div class="row tam">
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_esporte" class="checkbox_image esporte" type="checkbox" value="esporte" name="user_preferences[esporte]" />
                        <label for="habilidade_esporte">
                            <div class='content' name='div_eporte'>
                                <h4>Esporte</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_comunicacao" class="checkbox_image comunicacao" type="checkbox" value="comunicacao" name="user_preferences[comunicacao]" />
                        <label for="habilidade_comunicacao">
                            <div class='content'>
                                <h4>Comunicação e Marketing</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_cozinha" class="checkbox_image cozinha" type="checkbox" value="cozinha" name="user_habilidades[cozinha]" />
                        <label for="habilidade_cozinha">
                            <div class='content'>
                                <h4>Cozinha</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_ensinar" class="checkbox_image ensinar" type="checkbox" value="ensinar" name="user_preferences[cidadania][]" />
                        <label for="habilidade_ensinar">
                            <div class='content'>
                                <h4>Educação</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills[skill_experiences_attributes][0][skill_proficiency_id]">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_web" class="checkbox_image web" type="checkbox" value="web" name="user_preferences[web][]" />
                        <label for="habilidade_web">
                            <div class='content'>
                                <h4>Desenvolvimento web</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills[skill_experiences_attributes][0][skill_proficiency_id]">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_reformas" class="checkbox_image reformas" type="checkbox" value="reformas" name="user_preferences[reformas][]" />
                        <label for="habilidade_reformas">
                            <div class='content'>
                                <h4>Reformas</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills[skill_experiences_attributes][0][skill_proficiency_id]">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_decoracao" class="checkbox_image decoracao" type="checkbox" value="decoracao" name="user_preferences[decoracao][]" />
                        <label for="habilidade_decoracao">
                            <div class='content'>
                                <h4>Decoração</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills[skill_experiences_attributes][0][skill_proficiency_id]">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_comunitario" class="checkbox_image comunitario" type="checkbox" value="comunitario" name="user_preferences[comunitario][]" />
                        <label for="habilidade_comunitario">
                            <div class='content'>
                                <h4>Trabalho comunitário</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills[skill_experiences_attributes][0][skill_proficiency_id]">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->
                <!--Habilidades-->
                <div class='col-md-4 col-lg-4'>
                    <div class='skill_option'>
                        <input id="habilidade_outros" class="checkbox_image outros" type="checkbox" value="outros" name="user_preferences[outros][]" />
                        <label for="habilidade_outros">
                            <div class='content'>
                                <h4>Outros</h4>
                            </div>
                        </label>
                    </div>
                    <select class="form_input" id="skill_proficiency_6" name="user_skills[skill_experiences_attributes][0][skill_proficiency_id]">
                        <option value="">Selecionar nivel...</option>
                        <option value="1">Quero aprender</option>
                        <option value="2">Alguma experiência</option>
                        <option value="3">Expert!</option>
                    </select>
                </div>
                <!--Fim-->

            </div>
    </div>

    <div class='box_actions_outros'>
        <input type="submit" name="commit" value="Proseguir" class="btn btn_lg btn_primary" id="enviar" />
    </div>

    </form>
    </div>
    </div>


</body>

</html>