<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="utf-8">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Home Projetos</title>
</head>

<body>
  <a href="/logoff"></a>

  <!--Menu usuário logado-->
  <div class="header-main">
    <a href="index.html" class="logo"><b>C</b>olabora</a>
    <div class="w3layouts-right">
      <div class="profile_details_left">
        <!--notifications of menu start -->
        <ul class="nofitications-dropdown">
          <li class="dropdown head-dpdn">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
            <ul class="dropdown-menu">
              <li>
                <div class="notification_header">
                  <h3>You have 3 new messages</h3>
                </div>
              </li>
              <li><a href="#">
                  <div class="notification_desc">
                    <p>Lorem ipsum dolor</p>
                    <p><span>1 hour ago</span></p>
                  </div>
                  <div class="clearfix"></div>
                </a></li>
              <li>
                <div class="notification_bottom">
                  <a href="#">See all messages</a>
                </div>
              </li>
            </ul>
          </li>

        </ul>
      </div>

    </div>

    <div class="profile_details w3l">
      <ul>
        <li class="dropdown profile_details_drop">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <div class="profile_img">
              <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
              <div class="user-name">
                <p>Malorum</p>
                <span>Administrator</span>
              </div>
              <i class="fa fa-angle-down"></i>
              <i class="fa fa-angle-up"></i>
              <div class="clearfix"></div>
            </div>
          </a>
          <ul class="dropdown-menu drp-mnu">
            <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
            <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
            <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
            <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
          </ul>
        </li>
      </ul>
    </div>

    <div class="clearfix"> </div>
  </div>

  <div class="application_container container-fluid">
    <div class="row">
      <div class="col-md-8 col-lg-8 col-sm-10 col-md-offset-2 col-lg-offset-2 col-sm-offset-1">
        <form class="box" id="user_about_info" action="#" method="POST">
          <h1 class="mg_bot_40 ">Desenvolvimento de Sites</h1>
          <div class='box_content'>

            <div class="expander" data-text-expand="Ver mais detalhes" data-text-collapse="colapsar" data-slice-point="300" inline-expander="true" data-text-prefix="...">
              Gostaria de trabalhar para vocês para o investimento da empresa e o crescimento de atividades
              econômicas e conhecimento até para mim mesma e ao mesmo tempo fazer uma proposta de
              crescimento e rendimento para a empresa
            </div>
            <br><br>
            <strong>Categoria</strong>
            Ti programação

          </div>
          <br>
          <div class='box_actions'>
            <input type="submit" name="commit" value="Voluntariar-se" class="btn btn_lg btn_primary" />

          </div>
        </form>
      </div>
    </div>

  </div>
</body>

</html>