<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>perfil</title>
    <meta charset="UTF-8" />
</head>

<body>
    <div class='application_container container-fluid'>
        <div class='user-show'>
            <div class='content-container'>
                <div class='row user-profile'>
                    <div class='col-lg-2 col-md-2 col-sm-3 photo-wrapper'>
                        <a class="edit-photo-hover mg_bot_20" href="/fotos"><img class=" user-photo" src="icons/profile3.jpg" alt="Missing" /></a>
                    </div>
                    <div class='col-lg-10 col-md-10 col-sm-8'>
                        <h1 class='mg_bot_10'>Adriana Diniz</h1>
                        <div class='row'>
                            <div class='col-lg-6 col-md-5 user-profile__user-info mg_bot_20'>
                                <hr class='visible-xs'>
                                <ul class='basic-info-list'>
                                    <li>
                                        <p class='no_margin'>
                                            <strong>Idade:</strong>
                                            26
                                        </p>
                                    </li>
                                    <li>
                                        <p class='no_margin'>
                                            <strong>Nacionalidade:</strong>
                                            Brasil
                                        </p>
                                    </li>                                    
                                </ul>
                                <hr class='visible-xs'>
                            </div>
                            <div class='col-lg-6 col-md-7'>
                            </div>
                        </div>
                    </div>
                </div>

                
                <div class='visible-xs sticky_cta'></div>

                
                    <div class='box_bottom margin_top'>
                        <a class="btn btn_secondary btn_small hidden-lg hidden-sm hidden-md" data-toggle="modal" data-target="#new_language_modal" href="#">Adicionar idioma
                            <i class='icon icon-plus left sm'></i>
                        </a></div>
                </div>

                <div class='profile_box' id='profile-skills'>
                    <div class='profile_box_header'>
                        <h2>Habilidades</h2>
                        <a class="btn btn_secondary btn_small pull_right" href="/pt-BR/users/1493702/skills/edit?ref=profile">Editar
                            <i class='icon icon-pencil left'></i>
                        </a>
                    </div>
                    <div class='content'>
                    </div>
                </div>

                <div class='profile_box' id='profile-about'>
                    <div class='profile_box_header'>
                        <h2>Quem sou eu</h2>
                        <a class="btn btn_small btn_secondary pull_right" href="/pt-BR/users/1493702/about/edit?ref=profile">Editar
                            <i class='icon icon-pencil left'></i>
                        </a>
                    </div>
                    <div class='profile_section_content'>
                        <p>Conte um pouco mais sobre você para o mundo. Isso cria uma conexão profunda entre você e as pessoas, pode acreditar :)</p>
                    </div>
                </div>      
                    
  
</body>

</html>