<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <title>perfil</title>
    <meta charset="UTF-8" />
</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="index.html" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/in4.jpg" alt="foto de perfil usuário"> </span>
                            <div class="user-name">
                                <?php session_start();?>
                                <p><?php echo $_SESSION['nome'];?></p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
                       
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
    <div class='application_container container-fluid'>
        <div class='user-show'>
            <div class='content-container'>
                <div class='row user-profile'>
                    <div class='col-lg-2 col-md-2 col-sm-3 photo-wrapper'>
                        <a class="edit-photo-hover mg_bot_20" href="/fotos"><img class=" user-photo" src="icons/profile3.jpg" alt="Missing" /></a>
                    </div>
                    <div class='col-lg-10 col-md-10 col-sm-8'>
                        <h1 class='mg_bot_10'>Adriana Diniz</h1>
                        <div class='row'>
                            <div class='col-lg-6 col-md-5 user-profile__user-info mg_bot_20'>
                                <hr class='visible-xs'>
                                <ul class='basic-info-list'>
                                    <li>
                                        <p class='no_margin'>
                                            <strong>Idade:</strong>
                                            26
                                        </p>
                                    </li>
                                    <li>
                                        <p class='no_margin'>
                                            <strong>Nacionalidade:</strong>
                                            Brasil
                                        </p>
                                    </li>
                                </ul>
                                <hr class='visible-xs'>
                            </div>
                            <div class='col-lg-6 col-md-7'>
                            </div>
                        </div>
                    </div>
                </div>


                <div class='visible-xs sticky_cta'></div>


                <div class='box_bottom margin_top'>
                    <a class="btn btn_secondary btn_small hidden-lg hidden-sm hidden-md" data-toggle="modal" data-target="#new_language_modal" href="#">Adicionar idioma
                        <i class='icon icon-plus left sm'></i>
                    </a></div>
            </div>

            <div class='profile_box' id='profile-skills'>
                <div class='profile_box_header'>
                    <h2>Habilidades</h2>
                    <a class="btn btn_secondary btn_small pull_right" href="/habilidades">Editar
                        <i class='icon icon-pencil left'></i>
                    </a>
                </div>
                <div class='content'>
                </div>
            </div>

            <div class='profile_box' id='profile-about'>
                <div class='profile_box_header'>
                    <h2>Quem sou eu</h2>
                    <a class="btn btn_small btn_secondary pull_right" href="/quem_sou">Editar
                        <i class='icon icon-pencil left'></i>
                    </a>
                </div>
                <div class='profile_section_content'>
                    <p>Conte um pouco mais sobre você para o mundo. Isso cria uma conexão profunda entre você e as pessoas, pode acreditar :)</p>
                </div>
            </div>


</body>

</html>