<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <title>perfil</title>
    <meta charset="UTF-8" />
</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="index.html" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <nav class="menu_logado">
                <ul class="menu">
                    <li class="item"><a href="/index_projeto">Projetos</a></li>
                </ul>
            </nav>
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/in4.jpg" alt="foto de perfil usuário"> </span>
                            <div class="user-name">
                                <?php session_start(); ?>
                                <span>
                                    <p><?php echo $_SESSION['nome']; ?></p>
                                </span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>

                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
    <div class='application_container container-fluid'>
        <div class='user-show'>
            <div class='content-container'>
                <div class='row user-profile'>
                    <div class='col-lg-2 col-md-2 col-sm-3 photo-wrapper'>
                        <a class="edit-photo-hover mg_bot_20" href="/fotos"><img class=" user-photo" src="icons/profile3.jpg" alt="Missing" /></a>
                    </div>
                    <div class='col-lg-10 col-md-10 col-sm-8'>
                        <h1 class='mg_bot_10'>Adriana Diniz</h1>
                        <div class='row'>
                            <div class='col-lg-6 col-md-5 user-profile__user-info mg_bot_20'>
                                <hr class='visible-xs'>
                                <ul class='basic-info-list'>
                                    <li>
                                        <p class='no_margin'>
                                            <strong>Idade:</strong>
                                            26
                                        </p>
                                    </li>
                                    <li>
                                        <p class='no_margin'>
                                            <strong>Localidade:</strong>
                                            São Paulo
                                        </p>
                                    </li>

                                    <hr class='visible-xs'>
                            </div>
                            <div class='col-lg-6 col-md-7'>
                            </div>
                        </div>
                    </div>
                </div>

                <!--editar Habilidades-->
                <div class='profile_box' id='skills'>
                    <div class='profile_box_header'>
                        <h2>Habilidades</h2>
                        <a class="btn btn_secondary btn_small pull_right" href="/habilidades">
                            Editar
                        </a>
                    </div>
                    <div class='content_perfil'>
                        <div class='skill-level'>
                            <h5>Quero aprender</h5>
                            <div class='row'>
                                <ul>
                                    <div class='col-sm-12 col-md-6'>
                                        <li class='mg_bot_10'>
                                            <i class='icon icon-administration'></i>
                                            <span>Administração</span>
                                        </li>

                                    </div>
                                </ul>
                            </div>
                        </div>
                        <div class='skill-level'>
                            <h5>Expert!</h5>
                            <div class='row'>
                                <ul>
                                    <div class='col-sm-12 col-md-6'>
                                        <li class='mg_bot_10'>
                                            <i class='icon icon-cooking'></i>
                                            <span>Preparar Refeições</span>
                                        </li>

                                    </div>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!--editar Sobre Mim-->
                    <div class='profile_box' id='profile-about'>
                        <div class='profile_box_header'>
                            <h2>Sobre mim</h2>
                            <a class="btn btn_small btn_secondary pull_right" href="/quem_sou">
                                Editar
                            </a>
                        </div>
                        <div class='profile_section_content'>
                            <p>Sou uma pessoa feliz,
                                Amo muito a vida
                                E dela sou aprendiz;
                                Tenho várias paixões,
                                Mas, como qualquer um,
                                Possuo imperfeições.                                
                            </p>
                        </div>
                    </div>
                    <!--editar experiencias de vida -->
                    <div class="profile_box" id="profile-live">
                        <div class='profile_box_header'>
                            <h2>Experiências de vida</h2>
                            <a class="btn btn_secondary btn_small pull_right" href="/experiencias">
                            Editar
                            </a>
                        </div>
                        <h4>Educação</h4>
                        <p class='mg_bot_20'>TSI</p>
                        <h4>Experiências profissionais</h4>
                        <p class='mg_bot_20'>nenhuma</p>
                    </div>

</body>

</html>