<!DOCTYPE html>
<html lang='pt-BR'>

<head>
  <title>Projeto</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
</head>

<body>
  <?php
  /*$lista = $this->view->ListarProjetos();
      foreach ($lista as $key => $value) {
        echo $value."</br>";
      }*/
  ?>


  <a href="/logoff"></a>

  <!--Menu usuário logado-->
  <div class="header-main">
    <a href="/index" class="logo"><b>C</b>olabora</a>

    <div class="w3layouts-right">
      <nav class="menu_logado">
        <ul class="menu">
          <li class="item"><a href="/index_projeto">Projetos</a></li>
        </ul>
      </nav>
      <div class="profile_details_left">
        <!--notifications of menu start -->
        <ul class="nofitications-dropdown">
          <li class="dropdown head-dpdn">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
            <ul class="dropdown-menu">
              <li>
                <div class="notification_header">
                  <h3>You have 3 new messages</h3>
                </div>
              </li>
              <li><a href="#">
                  <div class="notification_desc">
                    <p>Lorem ipsum dolor</p>
                    <p><span>1 hour ago</span></p>
                  </div>
                  <div class="clearfix"></div>
                </a></li>
              <li>
                <div class="notification_bottom">
                  <a href="#">See all messages</a>
                </div>
              </li>
            </ul>
          </li>

        </ul>
      </div>

    </div>

    <div class="profile_details w3l">
      <ul>
        <li class="dropdown profile_details_drop">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <div class="profile_img">
              <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
              <div class="user-name">
                <p><?php echo $_SESSION['nome']; ?></p>
              </div>
              <i class="fa fa-angle-down"></i>
              <i class="fa fa-angle-up"></i>
              <div class="clearfix"></div>
            </div>
          </a>
          <ul class="dropdown-menu drp-mnu">
            <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
            <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
            <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
            <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
          </ul>
        </li>
      </ul>
    </div>

    <div class="clearfix"> </div>
  </div>


  <div class="container-fluid">
    <h1 class="h2 text_center">Publique seu projeto!</h1>
    <div class="box box_pro">
      <form class="register_form inactive" id="new_user" action="/salvarProjeto" method="POST">
        <div class="form-group">
          <label for="user_catego">Selecione Categoria</label>
          <select class="form_input gender_input" name="categoria" id="user_catego">
            <option value="">Categoria</option>
            <option value="1">Esporte</option>
            <option value="2">Comunicação e Marketing</option>
            <option value="3">Cozinha</option>
            <option value="4">Educação</option>
            <option value="5">Desenvolvimento web</option>
            <option value="6">Reformas</option>
            <option value="7">Decoração</option>
            <option value="8">Trabalho Comunitário</option>
          </select>
        </div>
        <div class="form-group">
          <label for="user_projeto">Nome Projeto</label>
          <input placeholder="Nome do Projeto" type="text" class="form_input name_input" id="user_projeto" name="nome_projeto">
        </div>
        <div class="form-group">
          <label for="comment">Descreva o trabalho a ser realizado</label>
          <textarea class="form-control" name="Comment" rows="10" id="comment" placeholder="iclua aqui todos os detalhes que puder, incluind informações de contato (e-amil, telefone, nome)"></textarea>
        </div>

        <input type="submit" name="comit" value="Publica Projeto" class="btn btn_lg btn_primary btn_block">
      </form>
    </div>
  </div>

</body>

</html>