<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8" />
	<title>Miniframework</title>

	
	<!-- Importação do css da aplicação local -->
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link href="css/styles.css" rel='stylesheet' type='text/css' media="all">
	<script src="js/responsive-nav.js"></script>
	<link href="css/font-awesome.css" rel="stylesheet" type="text/css">
	<script src="js/jquery-2.1.4.min.js"></script>

	<!-- Importação do js da aplicação local -->
	<script src="js/bootstrap.min.js"></script>
	<script src="js/fastclick.js"></script>
	<script src="js/scroll.js"></script>
	<script src="js/fixed-responsive-nav.js"></script>

</head>

<body>
	<?= $this->content() ?>
</body>

</html>