<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Miniframework</title>

	<!-- Importação bootstrap online -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<!-- Importação bootstrap.min.js online -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<!-- Importação jquery online -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

	<!-- Importação popper online -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

	<!-- Importação fontawesome online -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
		
	<!-- Importação do css da aplicação local -->
	<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    	<link href="css/styles.css" rel='stylesheet' type='text/css' media="all">
    	<script src="js/responsive-nav.js"></script>
    	<link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    	<script src="js/jquery-2.1.4.min.js"></script>

	<!-- Importação do js da aplicação local -->
	<script src="js/fastclick.js"></script>
    	<script src="js/scroll.js"></script>
    	<script src="js/fixed-responsive-nav.js"></script>
    	<script src="js/bootstrap.min.js"></script>
		

	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>	
