<!DOCTYPE html>
<html>

<head>
    <title>cadastro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="css/styles.css" rel='stylesheet' type='text/css' media="all">
    <script src="js/responsive-nav.js"></script>



</head>

<body>

<header>
    <a href="index.html" class="logo"><b>C</b>olabora</a>
    <nav class="nav-collapse">
        <ul>
            <li class="menu-item"><a href="#home" data-scroll>Como Funciona</a></li>
            <li class="menu-item"><a href="#about" data-scroll>Projetos</a></li>
            <li class="menu-item"><a href="login.html" data-scroll>Entrar</a></li>
            <li class="menu-item"><a href="cadastro.html" data-scroll>Registre-se</a></li>

        </ul>
    </nav>
</header>

    <section class="registration">
        <div class="container-fluid">
            <div class="box registration_box">
                <h1 class="h2 text_center">Registre-se</h1>
                <form class="register_form inactive" id="new_user" action="/registrar" method="POST">
                    <div class="form_group">
                        <input autofocus="autofocus" placeholder="Nome Completo" type="text" value="<?= $this->view->usuario['nome'] ?>"
                            class="form_input name_input" id="user_nome" name="nome">
                    </div>
                    <div class="form_group">
                        <input autofocus="autofocus" type="email" value="<?= $this->view->usuario['email'] ?>" class="form_input email_input" id="user_email"
                            placeholder="E-mail" name="email" required>
                    </div>
                    <div class="form_group">
                        <input autocomplete="off" type="password" value="<?= $this->view->usuario['senha'] ?>" class="form_input password_input" id="pwd"
                            placeholder="Sua senha" name="senha" required>
                        <div class="invalid-feedback">Entre com a senha</div>
                    </div>
                    <div class="form_group">
                        <select class="form_input gender_input" name="user_gender" id="user_gender">
                            <option value="">Escolha seu Gênero</option>
                            <option value="F">Feminino</option>
                            <option value="M">Masculino</option>
                            <option value="N">Neutro</option>
                        </select>
                    </div>
                    <div class="form_group">
                        <select class="form_input nationality_input" name="user_nationality" id="user_nationality">
                            <option value="">Estado</option>
                            <option value="AC">Acre</option>
                            <option value="AL">Alagoas</option>
                            <option value="AP">Amapá</option>
                            <option value="AM">Amazonas</option>
                            <option value="BA">Bahia</option>
                            <option value="CE">Ceará</option>
                            <option value="DF">Distrito Federal</option>
                            <option value="ES">Espírito Santo</option>
                            <option value="GO">Goiás</option>
                            <option value="MA">Maranhão</option>
                            <option value="MT">Mato Grosso</option>
                            <option value="MS">Mato Grosso do Sul</option>
                            <option value="MG">Minas Gerais</option>
                            <option value="PA">Pará</option>
                            <option value="PB">Paraíba</option>
                            <option value="PR">Paraná</option>
                            <option value="PE">Pernambuco</option>
                            <option value="PI">Piauí</option>
                            <option value="RJ">Rio de Janeiro</option>
                            <option value="RN">Rio Grande do Norte</option>
                            <option value="RS">Rio Grande do Sul</option>
                            <option value="RO">Rondônia</option>
                            <option value="RR">Roraima</option>
                            <option value="SC">Santa Catarina</option>
                            <option value="SP">São Paulo</option>
                            <option value="SE">Sergipe</option>
                            <option value="TO">Tocantins</option>
                            <option value="ES">Estrangeiro</option>
                        </select>
                    </div>
                    <div class="form_group">
                        <!-- <label class="block" for="user_aniversario">Seu aniversário?</label>
                        <select id="user_aniversario 3i" name="user[aniversario 3i]" class="form_input form_date">
                            <option value="">Dia</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                            <option value="20">20</option>
                            <option value="21">21</option>
                            <option value="22">22</option>
                            <option value="23">23</option>
                            <option value="24">24</option>
                            <option value="25">25</option>
                            <option value="26">26</option>
                            <option value="27">27</option>
                            <option value="28">28</option>
                            <option value="29">29</option>
                            <option value="30">30</option>
                            <option value="31">31</option>
                        </select>
                        <select id="user_aniversario 2i" name="aniversario[aniversario 2i]"
                            class="form_input form_date">
                            <option value="">Mês</option>
                            <option value="1">Janeiro</option>
                            <option value="2">Fevereiro</option>
                            <option value="3">Março</option>
                            <option value="4">Abril</option>
                            <option value="5">Maio</option>
                            <option value="6">Junho</option>
                            <option value="7">Julho</option>
                            <option value="8">Agosto</option>
                            <option value="9">Setembro</option>
                            <option value="10">Outubro</option>
                            <option value="11">Novembro</option>
                            <option value="12">Dezembro</option>
                        </select>
                        <select id="user_aniversario 1i" name="aniversario[aniversario 1i]"
                            class="form_input form_date">
                            <option class="">Ano</option>
                            <option value="2010">2010</option>
                            <option value="2009">2009</option>
                            <option value="2008">2008</option>
                            <option value="2007">2007</option>
                            <option value="2006">2006</option>
                            <option value="2005">2005</option>
                            <option value="2004">2004</option>
                            <option value="2003">2003</option>
                            <option value="2002">2002</option>
                            <option value="2001">2001</option>
                            <option value="2000">2000</option>
                            <option value="1999">1999</option>
                            <option value="1998">1998</option>
                            <option value="1997">1997</option>
                            <option value="1996">1996</option>
                            <option value="1995">1995</option>
                            <option value="1994">1994</option>
                            <option value="1993">1993</option>
                            <option value="1992">1992</option>
                            <option value="1993">1993</option>
                            <option value="1992">1992</option>
                            <option value="1991">1991</option>
                            <option value="1990">1990</option>
                            <option value="1989">1989</option>
                            <option value="1988">1988</option>
                            <option value="1987">1987</option>
                            <option value="1986">1986</option>
                            <option value="1985">1985</option>
                            <option value="1985">1985</option>
                            <option value="1984">1984</option>
                            <option value="1983">1983</option>
                            <option value="1982">1982</option>
                            <option value="1981">1981</option>
                            <option value="1980">1980</option>
                            <option value="1979">1979</option>
                            <option value="1979">1979</option>
                            <option value="1978">1978</option>
                            <option value="1977">1977</option>
                            <option value="1976">1976</option>
                            <option value="1975">1975</option>
                            <option value="1974">1975</option>
                            <option value="1973">1973</option>
                            <option value="1972">1972</option>
                            <option value="1971">1971</option>
                            <option value="1970">1970</option>
                            <option value="1969">1969</option>
                            <option value="1968">1968</option>
                            <option value="1967">1967</option>
                            <option value="1966">1966</option>
                            <option value="1965">1965</option>
                            <option value="1966">1966</option>
                            <option value="1965">1965</option>
                            <option value="1964">1964</option>
                            <option value="1963">1963</option>
                            <option value="1962">1962</option>
                            <option value="1961">1961</option>
                            <option value="1960">1960</option>
                            <option value="1959">1959</option>
                            <option value="1958">1958</option>
                            <option value="1957">1957</option>
                            <option value="1956">1956</option>
                            <option value="1955">1955</option>
                            <option value="1954">1954</option>
                            <option value="1953">1953</option>
                            <option value="1952">1952</option>
                            <option value="1951">1951</option>
                            <option value="1950">1950</option>
                            <option value="1949">1949</option>
                            <option value="1948">1948</option>
                            <option value="1947">1947</option>
                            <option value="1946">1946</option>
                            <option value="1945">1945</option>
                            <option value="1944">1944</option>
                            <option value="1943">1943</option>
                            <option value="1942">1942</option>
                            <option value="1942">1942</option>
                            <option value="1941">1941</option>
                            <option value="1940">1940</option>
                        </select> -->

                        Birthday: <input type="date" value="<?= $this->view->usuario['dt_nasc'] ?>" name="bday">

                    </div>
                    <div class="form_group">
                        <input class="form_input" data-form-check-box="" type="checkbox" value="" name="user_terms"
                            id="user_terms">
                        <label class="small" for="user_terms"> Eu aceito os <a href="#"> termos de uso </a> e <a
                                href="politica_privacidade.html"> privacidade </a> da
                            Colabora</label>
                    </div>
                    <input type="submit" name="comit" value="Registrar-se" class="btn btn_lg btn_primary btn_block">

                    <?php if($this->view->erroCadastro) { ?>
                        
                        <small class="form-text text-danger"> Erro ao tentar realizar cadastro! </small>
                   
                    <?php } ?>

                </form>
            </div>
            <h2 class="pt-4 h4 with_link text_center">
                Já é um membro?
                <br>
                <a href="login.html">Entrar</a>
            </h2>
        </div>
    </section>


    <script src="js/bootstrap.js"></script>
    <script src="js/fastclick.js"></script>
    <script src="js/scroll.js"></script>
    <script src="js/fixed-responsive-nav.js"></script>


</body>

</html>