<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>cadastro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

    <header class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>
        <nav class="nav-collapse">
            <ul>
                <li class="menu-item"><a href="/index#home">Sobre nós</a></li>
                <li class="menu-item"><a href="/index#equipe">Equipe</a></li>
                <li class="menu-item"><a href="/index_projeto">Projetos</a></li>
                <li class="menu-item"><a href="/login">Entrar</a></li>
                <li class="menu-item"><a href="/cadastro">Registre-se</a></li>

            </ul>
        </nav>
    </header>

    <section class="registration">
        <div class="container-fluid">
            <div class="box registration_box">
                <h1 class="h2 text_center">Registre-se</h1>
                <form class="register_form inactive needs-validation" id="new_user" action="/registrar" method="POST">

                    <div class="form-group">
                        <input autofocus="autofocus" placeholder="Nome Completo" type="text" class="form_input name_input" id="user_nome" name="nome" required>
                    </div>
                    <div class="form-group">
                        <input autofocus="autofocus" type="email" class="form_input email_input" id="user_email" placeholder="E-mail" name="email" required>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" type="password" class="form_input password_input" id="pwd" placeholder="Sua senha" name="senha" required>

                    </div>
                    <div class="form-group">
                        <select class="form_input gender_input" name="user_gender" id="user_gender">
                            <option value="">Escolha seu Gênero</option>
                            <option value="F">Feminino</option>
                            <option value="M">Masculino</option>
                            <option value="N">Neutro</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <select class="form_input nationality_input" name="user_nationality" id="user_nationality">
                            <option value="">Estado onde mora</option>
                            <option value="AC">Acre</option>
                            <option value="AL">Alagoas</option>
                            <option value="AP">Amapá</option>
                            <option value="AM">Amazonas</option>
                            <option value="BA">Bahia</option>
                            <option value="CE">Ceará</option>
                            <option value="DF">Distrito Federal</option>
                            <option value="ES">Espírito Santo</option>
                            <option value="GO">Goiás</option>
                            <option value="MA">Maranhão</option>
                            <option value="MT">Mato Grosso</option>
                            <option value="MS">Mato Grosso do Sul</option>
                            <option value="MG">Minas Gerais</option>
                            <option value="PA">Pará</option>
                            <option value="PB">Paraíba</option>
                            <option value="PR">Paraná</option>
                            <option value="PE">Pernambuco</option>
                            <option value="PI">Piauí</option>
                            <option value="RJ">Rio de Janeiro</option>
                            <option value="RN">Rio Grande do Norte</option>
                            <option value="RS">Rio Grande do Sul</option>
                            <option value="RO">Rondônia</option>
                            <option value="RR">Roraima</option>
                            <option value="SC">Santa Catarina</option>
                            <option value="SP">São Paulo</option>
                            <option value="SE">Sergipe</option>
                            <option value="TO">Tocantins</option>
                            <option value="ES">Estrangeiro</option>
                        </select>
                    </div>
                    <div class="form_group">
                        <label class="block" for="user_aniversario">Seu aniversário?</label>
                        <input type="date" name="bday" class="form_input">

                    </div>
                    <div class="form_group">
                        <input class="form_input" data-form-check-box="" type="checkbox" value="" name="user_terms" id="user_terms">
                        <label class="small" for="user_terms"> Eu aceito os <a href="#"> termos de uso </a> e <a href="politica_privacidade.html"> privacidade </a> da
                            Colabora</label>
                    </div>
                    <button type="submit" value="Registrar-se" class="btn btn_primary btn_block">Enviar</button>
                </form>
            </div>
            <h2 class="pt-4 h4 with_link text_center">
                Já é um membro?
                <br>
                <a href="/login">Entrar</a>
            </h2>
        </div>
    </section>



    <script>
        // Exemplo de JavaScript inicial para desativar envios de formulário, se houver campos inválidos.
        (function() {
            'use strict';
            window.addEventListener('load', function() {
                // Pega todos os formulários que nós queremos aplicar estilos de validação Bootstrap personalizados.
                var forms = document.getElementsByClassName('register_form inactive needs-validation');
                // Faz um loop neles e evita o envio
                var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>


</body>

</html>