<!DOCTYPE html>
<html>

<head>
    <title>Editar Cadastro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="css/styles.css" rel='stylesheet' type='text/css' media="all">
    <script src="js/responsive-nav.js"></script>
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    <script src="js/jquery-2.1.4.min.js"></script>
</head>

<body>

    <!--header start here-->
    <div class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/in4.jpg" alt=""> </span>
                            <div class="user-name">
                                <p>Anna Barbara</p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="cadastro_editar.html"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="#"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="#"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>


    <div class='application_container container-fluid'>
        <div class='row'>
            <div class='col-lg-4 col-md-4 mg_bot_20'>
                <div class='box'>
                    <ul>
                        <li>
                            <a class="block mg_bot_20" href="/pt-BR/me/account/edit">Informações básicas
                            </a></li>
                        <li>
                            <a class="block mg_bot_20" href="/pt-BR/users/1493702/contact_infos/new">Informações de contato
                            </a></li>
                        <li>
                            <a class="block mg_bot_20" href="/pt-BR/users/edit">Trocar minha senha
                            </a></li>
                        <li>
                            <a class="block mg_bot_20" href="/pt-BR/me/account/manage">Excluir conta &amp; opções de
                                Privacidade
                            </a></li>
                        <li>
                            <a class="block" href="/pt-BR/privacy">Termos de Privacidade
                            </a></li>
                    </ul>
                </div>

            </div>
            <div class="col-lg-8 col-md-8 mg_bot_20">
                <form class="box" id="edit_user" action="cadastro_editar" method="Post">
                    <h1>Informações Pessoais</h1>
                    <div class='box_content'>
                        <div class='row'>
                            <div class='form_group col-md-6 col-lg-6 col-sm-6'>
                                <label for="user_first_name">Primeiro nome</label>
                                <input class="form_input" type="text" value="Adriana Diniz" name="user[first_name]" id="user_first_name" />

                            </div>
                            <div class='form_group col-md-6 col-lg-6 col-sm-6'>
                                <label for="user_last_name">Sobrenome</label>
                                <input class="form_input" type="text" value="Ragazoni Bezerra" name="user[last_name]" id="user_last_name" />

                            </div>
                        </div>
                        <div class='form_group'>
                            <label for="user_email">Email</label>
                            <input class="form_input" type="email" value="dri.ragazoni@gmail.com" name="user[email]" id="user_email" />

                        </div>
                        <div class='row'>
                            <div class='form_group col-md-6 col-lg-6 col-sm-6'>
                                <label for="user_gender">Que pronome você prefere?</label>
                                <select class="form_input" name="user[gender]" id="user_gender">
                                    <option value="">Selecionar</option>
                                    <option selected="selected" value="F">Feminino &quot;Ela ama viajar!&quot;</option>
                                    <option value="M">Masculino &quot;Ele ama viajar!&quot;</option>
                                    <option value="N">Neutro &quot;Essa pessoa ama viajar!&quot;</option>
                                </select>

                            </div>
                            <div class='form_group col-md-6 col-lg-6 col-sm-6'>
                                <label class="block" for="user_birthday">Data de aniversário</label>
                                <input type="date" name="bday" class="form_input form_date">

                            </div>
                        </div>
                        <div class='form_group'>
                            <label class="label_lg" for="user_places_attributes_nationality">Nacionalidade</label>
                            <select class="form_input input_lg" name="user[places_attributes][nationality]" id="user_places_attributes_nationality">
                                <option value="">Escolha um país...</option>
                                <option value="The Gambia">A Gâmbia</option>
                                <option value="Afghanistan">Afeganistão</option>
                                <option value="South Africa">África do Sul</option>
                                <option value="Albania">Albânia</option>
                                <option value="Germany">Alemanha</option>
                                <option value="Andorra">Andorra</option>
                                <option value="Angola">Angola</option>
                                <option value="Anguilla">Anguilla</option>
                                <option value="Antarctica">Antártica</option>
                                <option value="Antigua and Barbuda">Antígua e Barbuda</option>
                                <option value="Netherlands Antilles">Antilhas Holandesas</option>
                                <option value="Saudi Arabia">Arábia Saudita</option>
                                <option value="Algeria">Argélia</option>
                                <option value="Argentina">Argentina</option>
                                <option value="Armenia">Armênia</option>
                                <option value="Aruba">Aruba</option>
                                <option value="The Bahamas">As Bahamas</option>
                                <option value="Ashmore and Cartier">Ashmore e Cartier</option>
                                <option value="Palmyra Atoll">Atol Palmyra</option>
                                <option value="Johnston Atoll">Atol de Johnston</option>
                                <option value="Australia">Austrália</option>
                                <option value="Austria">Áustria</option>
                                <option value="Azerbaijan">Azerbaijão</option>
                                <option value="Bahrain">Bahrein</option>
                                <option value="Baker Island">Baker Island</option>
                                <option value="Bangladesh">Bangladesh</option>
                                <option value="Barbados">Barbados</option>
                                <option value="Bassas da India">Bassas da Índia</option>
                                <option value="Belgium">Bélgica</option>
                                <option value="Belize">Belize</option>
                                <option value="Benin">Benin</option>
                                <option value="Bermuda">Bermudas</option>
                                <option value="Belarus">Bielorrússia</option>
                                <option value="Burma">Birmânia</option>
                                <option value="Bolivia">Bolívia</option>
                                <option value="Bosnia and Herzegovina">Bósnia e Herzegovina</option>
                                <option value="Botswana">Botswana</option>
                                <option selected="selected" value="Brazil">Brasil</option>
                                <option value="Brunei Darussalam">Brunei Darussalam</option>
                                <option value="Bulgaria">Bulgária</option>
                                <option value="Burkina Faso">Burkina Faso</option>
                                <option value="Burundi">Burundi</option>
                                <option value="Bhutan">Butão</option>
                                <option value="Cape Verde">Cabo Verde</option>
                                <option value="Cameroon">Camarões</option>
                                <option value="Cambodia">Camboja</option>
                                <option value="Canada">Canadá</option>
                                <option value="Qatar">Catar</option>
                                <option value="Kazakhstan">Cazaquistão</option>
                                <option value="Chad">Chade</option>
                                <option value="Chile">Chile</option>
                                <option value="China">China</option>
                                <option value="Cyprus">Chipre</option>
                                <option value="Singapore">Cingapura</option>
                                <option value="West Bank">Cisjordânia</option>
                                <option value="Colombia">Colômbia</option>
                                <option value="Comoros">Comores</option>
                                <option value="Congo, Democratic Republic of the">Congo, República Democrática do</option>
                                <option value="Congo, Republic of the">Congo, República da</option>
                                <option value="Korea, North">Coréia do Norte</option>
                                <option value="Korea, South">Coreia do Sul</option>
                                <option value="South Korea">Coreia do Sul</option>
                                <option value="Costa Rica">Costa Rica</option>
                                <option value="Cote d&#39;Ivoire">Costa do Marfim</option>
                                <option value="Croatia">Croácia</option>
                                <option value="Cuba">Cuba</option>
                                <option value="Denmark">Dinamarca</option>
                                <option value="Miscellaneous (French)">Diversos (Francês)</option>
                                <option value="Djibouti">Djibouti</option>
                                <option value="Dominica">Dominica</option>
                                <option value="Egypt">Egito</option>
                                <option value="El Salvador">El Salvador</option>
                                <option value="United Arab Emirates">Emirados Árabes Unidos</option>
                                <option value="Ecuador">Equador</option>
                                <option value="Eritrea">Eritreia</option>
                                <option value="Slovakia">Eslováquia</option>
                                <option value="Slovenia">Eslovênia</option>
                                <option value="Spain">Espanha</option>
                                <option value="State of Palestine">Estado da Palestina</option>
                                <option value="United States">Estados Unidos</option>
                                <option value="Estonia">Estônia</option>
                                <option value="Ethiopia">Etiópia</option>
                                <option value="Gaza Strip">Faixa de Gaza</option>
                                <option value="Fiji">Fiji</option>
                                <option value="Philippines">Filipinas</option>
                                <option value="Finland">Finlândia</option>
                                <option value="France">França</option>
                                <option value="France, Metropolitan">França, Metropolitan</option>
                                <option value="Gabon">Gabão</option>
                                <option value="Ghana">Gana</option>
                                <option value="Georgia">Geórgia</option>
                                <option value="South Georgia and the South Sandwich Islands">Geórgia do Sul e Ilhas Sandwich
                                    do Sul</option>
                                <option value="Gibraltar">Gibraltar</option>
                                <option value="Grenada">Granada</option>
                                <option value="Greece">Grécia</option>
                                <option value="Greenland">Groelândia</option>
                                <option value="Guadeloupe">Guadalupe</option>
                                <option value="Guam">Guam</option>
                                <option value="Guatemala">Guatemala</option>
                                <option value="Guernsey">Guernsey</option>
                                <option value="Guyana">Guiana</option>
                                <option value="French Guiana">Guiana Francesa</option>
                                <option value="Guinea">Guiné</option>
                                <option value="Equatorial Guinea">Guiné Equatorial</option>
                                <option value="Guinea-Bissau">Guiné-Bissau</option>
                                <option value="Haiti">Haiti</option>
                                <option value="Netherlands">Holanda</option>
                                <option value="Man, Isle of">Homem, Ilha de</option>
                                <option value="Honduras">Honduras</option>
                                <option value="Hong Kong (SAR)">Hong Kong (SAR)</option>
                                <option value="Hungary">Hungria</option>
                                <option value="Yemen">Iémen</option>
                                <option value="Bouvet Island">Ilha Bouvet</option>
                                <option value="Europa Island">Ilha Europa</option>
                                <option value="Heard Island and McDonald Islands">Ilha Heard e Ilhas McDonald</option>
                                <option value="Howland Island">Ilha Howland</option>
                                <option value="Navassa Island">Ilha Navassa</option>
                                <option value="Norfolk Island">Ilha Norfolk</option>
                                <option value="Tromelin Island">Ilha Tromelin</option>
                                <option value="Clipperton Island">Ilha de Clipperton</option>
                                <option value="Juan de Nova Island">Ilha de Juan de Nova</option>
                                <option value="Wake Island">Ilha de Wake</option>
                                <option value="Christmas Island">Ilha do Natal</option>
                                <option value="Cayman Islands">Ilhas Cayman</option>
                                <option value="Cocos (Keeling) Islands">Ilhas Cocos (Keeling)</option>
                                <option value="Cook Islands">Ilhas Cook</option>
                                <option value="Faroe Islands">Ilhas Faroe</option>
                                <option value="Glorioso Islands">Ilhas Gloriosas</option>
                                <option value="Falkland Islands (Islas Malvinas)">Ilhas Malvinas</option>
                                <option value="Northern Mariana Islands">Ilhas Marianas do Norte</option>
                                <option value="Marshall Islands">Ilhas Marshall</option>
                                <option value="United States Minor Outlying Islands">Ilhas Menores Distantes dos Estados
                                    Unidos</option>
                                <option value="Midway Islands">Ilhas Midway</option>
                                <option value="Paracel Islands">Ilhas Paracel</option>
                                <option value="Pitcairn Islands">Ilhas Pitcairn</option>
                                <option value="Solomon Islands">Ilhas Salomão</option>
                                <option value="Spratly Islands">Ilhas Spratly</option>
                                <option value="Turks and Caicos Islands">Ilhas Turks e Caicos</option>
                                <option value="Virgin Islands">Ilhas Virgens</option>
                                <option value="Virgin Islands (US)">Ilhas Virgens (EUA)</option>
                                <option value="Virgin Islands (UK)">Ilhas Virgens (Reino Unido)</option>
                                <option value="British Virgin Islands">Ilhas Virgens Britânicas</option>
                                <option value="Coral Sea Islands">Ilhas do Mar de Coral</option>
                                <option value="India">Índia</option>
                                <option value="Indonesia">Indonésia</option>
                                <option value="Iran">Irã</option>
                                <option value="Iraq">Iraque</option>
                                <option value="Ireland">Irlanda</option>
                                <option value="Iceland">Islândia</option>
                                <option value="Israel">Israel</option>
                                <option value="Italy">Itália</option>
                                <option value="Jamaica">Jamaica</option>
                                <option value="Jan Mayen">Jan Mayen</option>
                                <option value="Japan">Japão</option>
                                <option value="Jarvis Island">Jarvis Island</option>
                                <option value="Jersey">Jersey</option>
                                <option value="Jordan">Jordânia</option>
                                <option value="Yugoslavia">Jugoslávia</option>
                                <option value="Kosovo">Kosovo</option>
                                <option value="Kuwait">Kuwait</option>
                                <option value="Laos">Laos</option>
                                <option value="Lesotho">Lesoto</option>
                                <option value="Latvia">Letônia</option>
                                <option value="Lebanon">Líbano</option>
                                <option value="Liberia">Libéria</option>
                                <option value="Libya">Líbia</option>
                                <option value="Liechtenstein">Liechtenstein</option>
                                <option value="Lithuania">Lituânia</option>
                                <option value="Luxembourg">Luxemburgo</option>
                                <option value="Macao">Macau</option>
                                <option value="Macedonia, The Former Yugoslav Republic of">Macedônia</option>
                                <option value="Madagascar">Madagascar</option>
                                <option value="Malaysia">Malásia</option>
                                <option value="Malawi">Malawi</option>
                                <option value="Maldives">Maldivas</option>
                                <option value="Mali">Mali</option>
                                <option value="Malta">Malta</option>
                                <option value="Morocco">Marrocos</option>
                                <option value="Martinique">Martinica</option>
                                <option value="Mauritius">Maurício</option>
                                <option value="Mauritania">Mauritânia</option>
                                <option value="Mayotte">Mayotte</option>
                                <option value="Mexico">México</option>
                                <option value="Myanmar">Mianmar</option>
                                <option value="Micronesia, Federated States of">Micronésia, Estados Federados da</option>
                                <option value="Mozambique">Moçambique</option>
                                <option value="Moldova">Moldávia</option>
                                <option value="Monaco">Mônaco</option>
                                <option value="Mongolia">Mongólia</option>
                                <option value="Montenegro">Montenegro</option>
                                <option value="Montserrat">Montserrat</option>
                                <option value="Namibia">Namíbia</option>
                                <option value="Nauru">Nauru</option>
                                <option value="Nepal">Nepal</option>
                                <option value="Nicaragua">Nicarágua</option>
                                <option value="Niger">Níger</option>
                                <option value="Nigeria">Nigéria</option>
                                <option value="Niue">Niue</option>
                                <option value="Norway">Noruega</option>
                                <option value="New Caledonia">Nova Caledônia</option>
                                <option value="New Zealand">Nova Zelândia</option>
                                <option value="Oman">Omã</option>
                                <option value="Palau">Palau</option>
                                <option value="Palestinian Territory, Occupied">Palestina</option>
                                <option value="Panama">Panamá</option>
                                <option value="Papua New Guinea">Papua Nova Guiné</option>
                                <option value="Pakistan">Paquistão</option>
                                <option value="Paraguay">Paraguai</option>
                                <option value="Peru">Peru</option>
                                <option value="French Polynesia">Polinésia Francesa</option>
                                <option value="Poland">Polônia</option>
                                <option value="Puerto Rico">Porto Rico</option>
                                <option value="Portugal">Portugal</option>
                                <option value="Kenya">Quênia</option>
                                <option value="Kyrgyzstan">Quirguistão</option>
                                <option value="Kiribati">Quiribati</option>
                                <option value="Kingman Reef">Recife de Kingman</option>
                                <option value="United Kingdom">Reino Unido</option>
                                <option value="Central African Republic">República Centro-Africana</option>
                                <option value="Czech Republic">República Checa</option>
                                <option value="Dominican Republic">República Dominicana</option>
                                <option value="Réunion">Reunião</option>
                                <option value="Romania">Romênia</option>
                                <option value="Rwanda">Ruanda</option>
                                <option value="Russia">Rússia</option>
                                <option value="Western Sahara">Saara Ocidental</option>
                                <option value="Samoa">Samoa</option>
                                <option value="American Samoa">Samoa Americana</option>
                                <option value="Western Samoa">Samoa Ocidental</option>
                                <option value="San Marino">San Marino</option>
                                <option value="Saint Helena">Santa Helena</option>
                                <option value="Saint Lucia">Santa Lúcia</option>
                                <option value="Holy See (Vatican City)">Santa Sé (Cidade do Vaticano)</option>
                                <option value="Saint Kitts and Nevis">São Cristóvão e Névis</option>
                                <option value="Saint Pierre and Miquelon">São Pedro e Miquelon</option>
                                <option value="São Tomé and Príncipe">São Tomé e Príncipe</option>
                                <option value="Saint Vincent and the Grenadines">São Vicente e Granadinas</option>
                                <option value="Senegal">Senegal</option>
                                <option value="Sierra Leone">Serra Leoa</option>
                                <option value="Serbia">Sérvia</option>
                                <option value="Serbia and Montenegro">Sérvia e Montenegro</option>
                                <option value="Seychelles">Seychelles</option>
                                <option value="Syria">Síria</option>
                                <option value="Somalia">Somália</option>
                                <option value="Sri Lanka">Sri Lanka</option>
                                <option value="Swaziland">Suazilândia</option>
                                <option value="Sudan">Sudão</option>
                                <option value="Sweden">Suécia</option>
                                <option value="Switzerland">Suíça</option>
                                <option value="Suriname">Suriname</option>
                                <option value="Svalbard">Svalbard</option>
                                <option value="Thailand">Tailândia</option>
                                <option value="Taiwan">Taiwan</option>
                                <option value="Tajikistan">Tajiquistão</option>
                                <option value="Tanzania">Tanzânia</option>
                                <option value="French Southern and Antarctic Lands">Terras Francesas do Sul e da Antártida
                                </option>
                                <option value="British Indian Ocean Territory">Território britânico do Oceano Índico
                                </option>
                                <option value="East Timor">Timor Leste</option>
                                <option value="Togo">Togo</option>
                                <option value="Tokelau">Tokelau</option>
                                <option value="Tonga">Tonga</option>
                                <option value="Trinidad and Tobago">Trinidad e Tobago</option>
                                <option value="Tunisia">Tunísia</option>
                                <option value="Turkmenistan">Turcomenistão</option>
                                <option value="Turkey">Turquia</option>
                                <option value="Tuvalu">Tuvalu</option>
                                <option value="Ukraine">Ucrânia</option>
                                <option value="Uganda">Uganda</option>
                                <option value="Uruguay">Uruguai</option>
                                <option value="Uzbekistan">Uzbequistão</option>
                                <option value="Vanuatu">Vanuatu</option>
                                <option value="Venezuela">Venezuela</option>
                                <option value="Vietnam">Vietnã</option>
                                <option value="Wallis and Futuna">Wallis e Futuna</option>
                                <option value="Zaire">Zaire</option>
                                <option value="Zambia">Zâmbia</option>
                                <option value="Zimbabwe">Zimbábue</option>
                            </select>
                        </div>
                        <div class='row'>
                            <div class='form_group col-md-6 col-lg-6 col-sm-6 col-xs-6'>
                                <label class="label_lg" for="user_places_attributes_city">Cidade atual</label>
                                <input class="form_input input_lg" type="text" value="São Paulo" name="user[places_attributes][city]" id="user_places_attributes_city" />
                            </div>
                            <div class='form_group col-md-6 col-lg-6 col-sm-6 col-xs-6'>
                                <label class="label_lg" for="user_places_attributes_country">País atual</label>
                                <select class="form_input input_lg" name="user[places_attributes][country]" id="user_places_attributes_country">
                                    <option value="">Escolha um país...</option>
                                    <option value="The Gambia">A Gâmbia</option>
                                    <option value="Afghanistan">Afeganistão</option>
                                    <option value="South Africa">África do Sul</option>
                                    <option value="Albania">Albânia</option>
                                    <option value="Germany">Alemanha</option>
                                    <option value="Andorra">Andorra</option>
                                    <option value="Angola">Angola</option>
                                    <option value="Anguilla">Anguilla</option>
                                    <option value="Antarctica">Antártica</option>
                                    <option value="Antigua and Barbuda">Antígua e Barbuda</option>
                                    <option value="Netherlands Antilles">Antilhas Holandesas</option>
                                    <option value="Saudi Arabia">Arábia Saudita</option>
                                    <option value="Algeria">Argélia</option>
                                    <option value="Argentina">Argentina</option>
                                    <option value="Armenia">Armênia</option>
                                    <option value="Aruba">Aruba</option>
                                    <option value="The Bahamas">As Bahamas</option>
                                    <option value="Ashmore and Cartier">Ashmore e Cartier</option>
                                    <option value="Palmyra Atoll">Atol Palmyra</option>
                                    <option value="Johnston Atoll">Atol de Johnston</option>
                                    <option value="Australia">Austrália</option>
                                    <option value="Austria">Áustria</option>
                                    <option value="Azerbaijan">Azerbaijão</option>
                                    <option value="Bahrain">Bahrein</option>
                                    <option value="Baker Island">Baker Island</option>
                                    <option value="Bangladesh">Bangladesh</option>
                                    <option value="Barbados">Barbados</option>
                                    <option value="Bassas da India">Bassas da Índia</option>
                                    <option value="Belgium">Bélgica</option>
                                    <option value="Belize">Belize</option>
                                    <option value="Benin">Benin</option>
                                    <option value="Bermuda">Bermudas</option>
                                    <option value="Belarus">Bielorrússia</option>
                                    <option value="Burma">Birmânia</option>
                                    <option value="Bolivia">Bolívia</option>
                                    <option value="Bosnia and Herzegovina">Bósnia e Herzegovina</option>
                                    <option value="Botswana">Botswana</option>
                                    <option selected="selected" value="Brazil">Brasil</option>
                                    <option value="Brunei Darussalam">Brunei Darussalam</option>
                                    <option value="Bulgaria">Bulgária</option>
                                    <option value="Burkina Faso">Burkina Faso</option>
                                    <option value="Burundi">Burundi</option>
                                    <option value="Bhutan">Butão</option>
                                    <option value="Cape Verde">Cabo Verde</option>
                                    <option value="Cameroon">Camarões</option>
                                    <option value="Cambodia">Camboja</option>
                                    <option value="Canada">Canadá</option>
                                    <option value="Qatar">Catar</option>
                                    <option value="Kazakhstan">Cazaquistão</option>
                                    <option value="Chad">Chade</option>
                                    <option value="Chile">Chile</option>
                                    <option value="China">China</option>
                                    <option value="Cyprus">Chipre</option>
                                    <option value="Singapore">Cingapura</option>
                                    <option value="West Bank">Cisjordânia</option>
                                    <option value="Colombia">Colômbia</option>
                                    <option value="Comoros">Comores</option>
                                    <option value="Congo, Democratic Republic of the">Congo, República Democrática do
                                    </option>
                                    <option value="Congo, Republic of the">Congo, República da</option>
                                    <option value="Korea, North">Coréia do Norte</option>
                                    <option value="Korea, South">Coreia do Sul</option>
                                    <option value="South Korea">Coreia do Sul</option>
                                    <option value="Costa Rica">Costa Rica</option>
                                    <option value="Cote d&#39;Ivoire">Costa do Marfim</option>
                                    <option value="Croatia">Croácia</option>
                                    <option value="Cuba">Cuba</option>
                                    <option value="Denmark">Dinamarca</option>
                                    <option value="Miscellaneous (French)">Diversos (Francês)</option>
                                    <option value="Djibouti">Djibouti</option>
                                    <option value="Dominica">Dominica</option>
                                    <option value="Egypt">Egito</option>
                                    <option value="El Salvador">El Salvador</option>
                                    <option value="United Arab Emirates">Emirados Árabes Unidos</option>
                                    <option value="Ecuador">Equador</option>
                                    <option value="Eritrea">Eritreia</option>
                                    <option value="Slovakia">Eslováquia</option>
                                    <option value="Slovenia">Eslovênia</option>
                                    <option value="Spain">Espanha</option>
                                    <option value="State of Palestine">Estado da Palestina</option>
                                    <option value="United States">Estados Unidos</option>
                                    <option value="Estonia">Estônia</option>
                                    <option value="Ethiopia">Etiópia</option>
                                    <option value="Gaza Strip">Faixa de Gaza</option>
                                    <option value="Fiji">Fiji</option>
                                    <option value="Philippines">Filipinas</option>
                                    <option value="Finland">Finlândia</option>
                                    <option value="France">França</option>
                                    <option value="France, Metropolitan">França, Metropolitan</option>
                                    <option value="Gabon">Gabão</option>
                                    <option value="Ghana">Gana</option>
                                    <option value="Georgia">Geórgia</option>
                                    <option value="South Georgia and the South Sandwich Islands">Geórgia do Sul e Ilhas
                                        Sandwich do Sul</option>
                                    <option value="Gibraltar">Gibraltar</option>
                                    <option value="Grenada">Granada</option>
                                    <option value="Greece">Grécia</option>
                                    <option value="Greenland">Groelândia</option>
                                    <option value="Guadeloupe">Guadalupe</option>
                                    <option value="Guam">Guam</option>
                                    <option value="Guatemala">Guatemala</option>
                                    <option value="Guernsey">Guernsey</option>
                                    <option value="Guyana">Guiana</option>
                                    <option value="French Guiana">Guiana Francesa</option>
                                    <option value="Guinea">Guiné</option>
                                    <option value="Equatorial Guinea">Guiné Equatorial</option>
                                    <option value="Guinea-Bissau">Guiné-Bissau</option>
                                    <option value="Haiti">Haiti</option>
                                    <option value="Netherlands">Holanda</option>
                                    <option value="Man, Isle of">Homem, Ilha de</option>
                                    <option value="Honduras">Honduras</option>
                                    <option value="Hong Kong (SAR)">Hong Kong (SAR)</option>
                                    <option value="Hungary">Hungria</option>
                                    <option value="Yemen">Iémen</option>
                                    <option value="Bouvet Island">Ilha Bouvet</option>
                                    <option value="Europa Island">Ilha Europa</option>
                                    <option value="Heard Island and McDonald Islands">Ilha Heard e Ilhas McDonald</option>
                                    <option value="Howland Island">Ilha Howland</option>
                                    <option value="Navassa Island">Ilha Navassa</option>
                                    <option value="Norfolk Island">Ilha Norfolk</option>
                                    <option value="Tromelin Island">Ilha Tromelin</option>
                                    <option value="Clipperton Island">Ilha de Clipperton</option>
                                    <option value="Juan de Nova Island">Ilha de Juan de Nova</option>
                                    <option value="Wake Island">Ilha de Wake</option>
                                    <option value="Christmas Island">Ilha do Natal</option>
                                    <option value="Cayman Islands">Ilhas Cayman</option>
                                    <option value="Cocos (Keeling) Islands">Ilhas Cocos (Keeling)</option>
                                    <option value="Cook Islands">Ilhas Cook</option>
                                    <option value="Faroe Islands">Ilhas Faroe</option>
                                    <option value="Glorioso Islands">Ilhas Gloriosas</option>
                                    <option value="Falkland Islands (Islas Malvinas)">Ilhas Malvinas</option>
                                    <option value="Northern Mariana Islands">Ilhas Marianas do Norte</option>
                                    <option value="Marshall Islands">Ilhas Marshall</option>
                                    <option value="United States Minor Outlying Islands">Ilhas Menores Distantes dos Estados
                                        Unidos</option>
                                    <option value="Midway Islands">Ilhas Midway</option>
                                    <option value="Paracel Islands">Ilhas Paracel</option>
                                    <option value="Pitcairn Islands">Ilhas Pitcairn</option>
                                    <option value="Solomon Islands">Ilhas Salomão</option>
                                    <option value="Spratly Islands">Ilhas Spratly</option>
                                    <option value="Turks and Caicos Islands">Ilhas Turks e Caicos</option>
                                    <option value="Virgin Islands">Ilhas Virgens</option>
                                    <option value="Virgin Islands (US)">Ilhas Virgens (EUA)</option>
                                    <option value="Virgin Islands (UK)">Ilhas Virgens (Reino Unido)</option>
                                    <option value="British Virgin Islands">Ilhas Virgens Britânicas</option>
                                    <option value="Coral Sea Islands">Ilhas do Mar de Coral</option>
                                    <option value="India">Índia</option>
                                    <option value="Indonesia">Indonésia</option>
                                    <option value="Iran">Irã</option>
                                    <option value="Iraq">Iraque</option>
                                    <option value="Ireland">Irlanda</option>
                                    <option value="Iceland">Islândia</option>
                                    <option value="Israel">Israel</option>
                                    <option value="Italy">Itália</option>
                                    <option value="Jamaica">Jamaica</option>
                                    <option value="Jan Mayen">Jan Mayen</option>
                                    <option value="Japan">Japão</option>
                                    <option value="Jarvis Island">Jarvis Island</option>
                                    <option value="Jersey">Jersey</option>
                                    <option value="Jordan">Jordânia</option>
                                    <option value="Yugoslavia">Jugoslávia</option>
                                    <option value="Kosovo">Kosovo</option>
                                    <option value="Kuwait">Kuwait</option>
                                    <option value="Laos">Laos</option>
                                    <option value="Lesotho">Lesoto</option>
                                    <option value="Latvia">Letônia</option>
                                    <option value="Lebanon">Líbano</option>
                                    <option value="Liberia">Libéria</option>
                                    <option value="Libya">Líbia</option>
                                    <option value="Liechtenstein">Liechtenstein</option>
                                    <option value="Lithuania">Lituânia</option>
                                    <option value="Luxembourg">Luxemburgo</option>
                                    <option value="Macao">Macau</option>
                                    <option value="Macedonia, The Former Yugoslav Republic of">Macedônia</option>
                                    <option value="Madagascar">Madagascar</option>
                                    <option value="Malaysia">Malásia</option>
                                    <option value="Malawi">Malawi</option>
                                    <option value="Maldives">Maldivas</option>
                                    <option value="Mali">Mali</option>
                                    <option value="Malta">Malta</option>
                                    <option value="Morocco">Marrocos</option>
                                    <option value="Martinique">Martinica</option>
                                    <option value="Mauritius">Maurício</option>
                                    <option value="Mauritania">Mauritânia</option>
                                    <option value="Mayotte">Mayotte</option>
                                    <option value="Mexico">México</option>
                                    <option value="Myanmar">Mianmar</option>
                                    <option value="Micronesia, Federated States of">Micronésia, Estados Federados da
                                    </option>
                                    <option value="Mozambique">Moçambique</option>
                                    <option value="Moldova">Moldávia</option>
                                    <option value="Monaco">Mônaco</option>
                                    <option value="Mongolia">Mongólia</option>
                                    <option value="Montenegro">Montenegro</option>
                                    <option value="Montserrat">Montserrat</option>
                                    <option value="Namibia">Namíbia</option>
                                    <option value="Nauru">Nauru</option>
                                    <option value="Nepal">Nepal</option>
                                    <option value="Nicaragua">Nicarágua</option>
                                    <option value="Niger">Níger</option>
                                    <option value="Nigeria">Nigéria</option>
                                    <option value="Niue">Niue</option>
                                    <option value="Norway">Noruega</option>
                                    <option value="New Caledonia">Nova Caledônia</option>
                                    <option value="New Zealand">Nova Zelândia</option>
                                    <option value="Oman">Omã</option>
                                    <option value="Palau">Palau</option>
                                    <option value="Palestinian Territory, Occupied">Palestina</option>
                                    <option value="Panama">Panamá</option>
                                    <option value="Papua New Guinea">Papua Nova Guiné</option>
                                    <option value="Pakistan">Paquistão</option>
                                    <option value="Paraguay">Paraguai</option>
                                    <option value="Peru">Peru</option>
                                    <option value="French Polynesia">Polinésia Francesa</option>
                                    <option value="Poland">Polônia</option>
                                    <option value="Puerto Rico">Porto Rico</option>
                                    <option value="Portugal">Portugal</option>
                                    <option value="Kenya">Quênia</option>
                                    <option value="Kyrgyzstan">Quirguistão</option>
                                    <option value="Kiribati">Quiribati</option>
                                    <option value="Kingman Reef">Recife de Kingman</option>
                                    <option value="United Kingdom">Reino Unido</option>
                                    <option value="Central African Republic">República Centro-Africana</option>
                                    <option value="Czech Republic">República Checa</option>
                                    <option value="Dominican Republic">República Dominicana</option>
                                    <option value="Réunion">Reunião</option>
                                    <option value="Romania">Romênia</option>
                                    <option value="Rwanda">Ruanda</option>
                                    <option value="Russia">Rússia</option>
                                    <option value="Western Sahara">Saara Ocidental</option>
                                    <option value="Samoa">Samoa</option>
                                    <option value="American Samoa">Samoa Americana</option>
                                    <option value="Western Samoa">Samoa Ocidental</option>
                                    <option value="San Marino">San Marino</option>
                                    <option value="Saint Helena">Santa Helena</option>
                                    <option value="Saint Lucia">Santa Lúcia</option>
                                    <option value="Holy See (Vatican City)">Santa Sé (Cidade do Vaticano)</option>
                                    <option value="Saint Kitts and Nevis">São Cristóvão e Névis</option>
                                    <option value="Saint Pierre and Miquelon">São Pedro e Miquelon</option>
                                    <option value="São Tomé and Príncipe">São Tomé e Príncipe</option>
                                    <option value="Saint Vincent and the Grenadines">São Vicente e Granadinas</option>
                                    <option value="Senegal">Senegal</option>
                                    <option value="Sierra Leone">Serra Leoa</option>
                                    <option value="Serbia">Sérvia</option>
                                    <option value="Serbia and Montenegro">Sérvia e Montenegro</option>
                                    <option value="Seychelles">Seychelles</option>
                                    <option value="Syria">Síria</option>
                                    <option value="Somalia">Somália</option>
                                    <option value="Sri Lanka">Sri Lanka</option>
                                    <option value="Swaziland">Suazilândia</option>
                                    <option value="Sudan">Sudão</option>
                                    <option value="Sweden">Suécia</option>
                                    <option value="Switzerland">Suíça</option>
                                    <option value="Suriname">Suriname</option>
                                    <option value="Svalbard">Svalbard</option>
                                    <option value="Thailand">Tailândia</option>
                                    <option value="Taiwan">Taiwan</option>
                                    <option value="Tajikistan">Tajiquistão</option>
                                    <option value="Tanzania">Tanzânia</option>
                                    <option value="French Southern and Antarctic Lands">Terras Francesas do Sul e da
                                        Antártida</option>
                                    <option value="British Indian Ocean Territory">Território britânico do Oceano Índico
                                    </option>
                                    <option value="East Timor">Timor Leste</option>
                                    <option value="Togo">Togo</option>
                                    <option value="Tokelau">Tokelau</option>
                                    <option value="Tonga">Tonga</option>
                                    <option value="Trinidad and Tobago">Trinidad e Tobago</option>
                                    <option value="Tunisia">Tunísia</option>
                                    <option value="Turkmenistan">Turcomenistão</option>
                                    <option value="Turkey">Turquia</option>
                                    <option value="Tuvalu">Tuvalu</option>
                                    <option value="Ukraine">Ucrânia</option>
                                    <option value="Uganda">Uganda</option>
                                    <option value="Uruguay">Uruguai</option>
                                    <option value="Uzbekistan">Uzbequistão</option>
                                    <option value="Vanuatu">Vanuatu</option>
                                    <option value="Venezuela">Venezuela</option>
                                    <option value="Vietnam">Vietnã</option>
                                    <option value="Wallis and Futuna">Wallis e Futuna</option>
                                    <option value="Zaire">Zaire</option>
                                    <option value="Zambia">Zâmbia</option>
                                    <option value="Zimbabwe">Zimbábue</option>
                                </select>
                            </div>
                        </div>
                        <input type="hidden" value="1142843" name="user[places_attributes][id]" id="user_places_attributes_id" />
                    </div>
                    <div class='box_actions'>
                        <button name="button" type="submit" class="btn btn_lg btn_primary" data-disable-with="Salvando...">Salvar
                        </button></div>
                </form>
            </div>
        </div>

    </div>

    <script src="js/fastclick.js"></script>
    <script src="js/scroll.js"></script>
    <script src="js/fixed-responsive-nav.js"></script>
    <script src="js/bootstrap.min.js"></script>


</body>

</html>