<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Fotos</title>
    <meta charset="UTF-8" />
</head>

<body>

    <div class='application_container container-fluid'>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-10 form_photo">
                <form class="box registration_box" id="edit_user_photo" action="/fotos" method="post">
                    <h1 class='mg_bot_20'>Escolher foto</h1>
                    <div class='box_content'>
                        <div class='row'>
                            <div class='col-lg-5 col-md-5 col-sm-6 text_center'>
                                <div class='small-row'>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 1" />
                                    </div>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 2" />
                                    </div>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 3" />
                                    </div>
                                    <div class='small-col-lg-6 small-col-md-6 small-col-sm-6 small-col-xs-3 cover_example'>
                                        <img class="avatar avatar_sq avatar_block" src="icons/picture.png" alt="Avatar 4" />
                                    </div>
                                </div>
                            </div>
                            <div class='col-lg-7 col-md-7 col-sm-6'>
                                <h4>Sua foto vai causar a primeira impressão!!! </h4>
                                <p>Lembre-se de escolher uma que mostre seu rosto, <br>
                                    Evite fotos com bichinhos, paisagens ou em grupo.</p>
                            </div>
                        </div>
                    </div>
                    <div class='form-group'>
                        <input class="form_input" type="file" name="photo" id="user_photo" />
                    </div>
                    <div class='box_actions'>
                        <input type="submit" name="commit" value="Fazer upload" class="btn btn_lg btn_primary" data-disable-with="Uploadando..." id="upload_avatar" />
                    </div>
                </form>
            </div>
        </div>

    </div>
</body>

</html>