<!DOCTYPE html>
<html>
    <head>
        <title>Idiomas</title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
            <link href="css/style.css" rel='stylesheet' type='text/css' media="all">
            
            
    </head>

    <body>
    <header>          
            <div>
                <div class="w3-bar w3-white w3-wide w3-padding w3-card">
                    <a href="index.html" class="w3-bar-item w3-button"><b>C</b>olabora</a>
                    <!-- Float links to the right. Hide them on small screens -->
                    <div class="w3-right w3-hide-small">
                        <a href="#projects" class="w3-bar-item w3-button">Como funciona</a>
                        <a href="#projects" class="w3-bar-item w3-button">Projetos</a>
                        <a href="login.html" class="w3-bar-item w3-button">Entrar</a>
                        <a href="cadastro.html" class="w3-bar-item w3-button">Cadastre-se</a>
                    </div>
                </div>
            </div>
    </header>

        <script src="js/bootstrap.js"></script>
        <script src="js/jquery-3.1.0.js"></script>
    </body>

</html>