<!DOCTYPE html>
<html>

<head>
    <title>Idiomas</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="css/styles.css" rel='stylesheet' type='text/css' media="all">
    <script src="js/responsive-nav.js"></script>


</head>

<body>

    <header>
        <a href="index.html" class="logo"><b>C</b>olabora</a>
        <nav class="nav-collapse">
            <ul>
                <li class="menu-item"><a href="#home" data-scroll>Como Funciona</a></li>
                <li class="menu-item"><a href="#about" data-scroll>Projetos</a></li>
                <li class="menu-item"><a href="login.html" data-scroll>Entrar</a></li>
                <li class="menu-item"><a href="cadastro.html" data-scroll>Registre-se</a></li>
    
            </ul>
        </nav>
    </header>

    <section>
        <div class="con">

        </div>
    </section>


    <script src="js/fastclick.js"></script>
    <script src="js/scroll.js"></script>
    <script src="js/fixed-responsive-nav.js"></script>
    <script src="js/bootstrap.js"></script>
</body>

</html>