<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home Projetos</title>
</head>

<body>
    <header class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>
        <nav class="nav-collapse">
            <ul>
                <li class="menu-item"><a href="/index#home">Sobre nós</a></li>
                <li class="menu-item"><a href="/index#equipe">Equipe</a></li>
                <li class="menu-item"><a href="/index_projeto">Projetos</a></li>
                <li class="menu-item"><a href="/login">Entrar</a></li>
                <li class="menu-item"><a href="/cadastro">Registre-se</a></li>

            </ul>
        </nav>
    </header>
    <div class="clearfix"> </div>

    <?php foreach ($this->view->projetos as $id_projeto => $projeto) { ?>
        <div class="application_container container-fluid">
            <div class="row">
                <div class="col-md-8 col-lg-8 col-sm-10 col-md-offset-2 col-lg-offset-2 col-sm-offset-1">
                    <form class="box" id="user_about_info" action="#" method="POST">
                        <h1 class="mg_bot_40 "><?= $projeto['nome_projeto'] ?></h1>
                        <div class='box_content'>

                            <div class="expander" data-text-expand="Ver mais detalhes" data-text-collapse="colapsar" data-slice-point="300" inline-expander="true" data-text-prefix="...">
                                <?= $projeto['descricao'] ?>
                            </div>
                            <br><br>
                            <strong>Categoria:</strong>
                            <?= $projeto['nome_categoria'] ?>
                            <br><br>
                            <strong>Data:</strong>
                            <?= $projeto['data'] ?>

                        </div>
                        <br>
                        <div class='box_actions'>
                            <input type="submit" name="commit" value="Voluntariar-se" class="btn btn_lg btn_primary" />
                        </div>
                    </form>
                </div>
            </div>

        </div>
    <?php } ?>

</body>

</html>