<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Home</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link href="css/styles.css" rel='stylesheet' type='text/css'>
  <link href="css/css_slider.css" type="text/css" rel="stylesheet">
  <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
  <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>

<body>
  <header class="header-main">
    <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>
    <nav class="nav-collapse">
      <ul>
        <li class="menu-item"><a href="#home" data-scroll>Como Funciona</a></li>
        <li class="menu-item"><a href="#about" data-scroll>Projetos</a></li>
        <li class="menu-item"><a href="/login" data-scroll>Entrar</a></li>
        <li class="menu-item"><a href="/cadastro" data-scroll>Registre-se</a></li>

      </ul>
    </nav>
  </header>

  <!-- banner -->
  <div class="banner_w3lspvt">
    <div class="csslider infinity" id="slider1">
      <input type="radio" name="slides" checked="checked" id="slides_1" />
      <input type="radio" name="slides" id="slides_2" />
      <input type="radio" name="slides" id="slides_3" />
      <ul class="banner_slide_bg">
        <li>
          <div class="container-fluid">
            <div class="w3ls_banner_txt">
              <h3><span>Seja um</span>Voluntário</h3>
              <p class="w3ls_pvt-title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in elementum
                turpis.</p>
              <p class="w3ls_pvt-title mt-2">Morbi posuere elementum orci, id molestie ligula tristique infres.</p>
              <a href="about.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
            </div>
          </div>
        </li>
        <li>
          <div class="container-fluid">
            <div class="w3ls_banner_txt">
              <h3><span>Mudança</span>Social</h3>
              <p class="w3ls_pvt-title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in elementum
                turpis.</p>
              <p class="w3ls_pvt-title mt-2">Morbi posuere elementum orci, id molestie ligula tristique infres.</p>
              <a href="about.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
            </div>
          </div>
        </li>
        <li>
          <div class="container-fluid">
            <div class="w3ls_banner_txt">
              <h3><span>Mude o Mundo</span>de Alguém</h3>
              <p class="w3ls_pvt-title">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in elementum
                turpis.</p>
              <p class="w3ls_pvt-title mt-2">Morbi posuere elementum orci, id molestie ligula tristique infres.</p>
              <a href="about.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
            </div>
          </div>
        </li>
      </ul>
      <div class="navigation">
        <div>
          <label for="slides_1"></label>
          <label for="slides_2"></label>
          <label for="slides_3"></label>
        </div>
      </div>
    </div>
  </div>
  <!-- //banner -->
  </div>
  <!-- //main banner -->

  <section class="conteudo" id="home">
    <h1>Como Funciona</h1>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>


  </section>

  <section class="conteudo" id="about">
    <h1>Projetos</h1>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
    <p></p>
  </section>


  <script src="js/jquery-2.1.4.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/fastclick.js"></script>
  <script src="js/scroll.js"></script>
  <script src="js/fixed-responsive-nav.js"></script>
</body>

</html>