<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Home</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">



</head>

<body>
  <header class="header-main">
    <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>
    <nav class="nav-collapse">
      <ul>
        <li class="menu-item"><a href="#home">Sobre nós</a></li>
        <li class="menu-item"><a href="#equipe">Equipe</a></li>
        <li class="menu-item"><a href="/index_projeto">Projetos</a></li>
        <li class="menu-item"><a href="/login">Entrar</a></li>
        <li class="menu-item"><a href="/cadastro">Registre-se</a></li>

      </ul>
    </nav>
  </header>

  <!-- banner -->
  <div class="banner_w3lspvt">
    <div class="csslider infinity" id="slider1">
      <input type="radio" name="slides" id="slides_1" />
      <input type="radio" name="slides" id="slides_2" />
      <input type="radio" name="slides" id="slides_3" />
      <ul class="banner_slide_bg">
        <li>
          <div class="container-fluid">
            <div class="w3ls_banner_txt">
              <h3><span>Importância</span>Social</h3>
              <p class="w3ls_pvt-title">
                O trabalho voluntário, além de ter importância social, propociona bem-estar e alegria
                a quem realiza,ao mesmo tempo em que eleva a autoestima, melhora a ansiedade e pode até mesmo
                prevenir doenças como depresão
              </p>
              <p class="w3ls_pvt-title mt-2">Seja um voluntário.</p>
              <a href="/cadastro" class="btn button-style mt-sm-5 mt-4">Inscreva-se</a>
            </div>
          </div>
        </li>
        <li>
          <div class="container-fluid">
            <div class="w3ls_banner_txt">
              <h3><span>A melhor</span>opção</h3>
              <p class="w3ls_pvt-title">
                É um bom momento para treinar o que você aprende: escolher uma atividade ligada a sua
                área é a melhro opção.
              </p>
              <p class="w3ls_pvt-title mt-2">Mudança Social</p>
              <a href="/cadastro" class="btn button-style mt-sm-5 mt-4">Inscreva-se</a>
            </div>
          </div>
        </li>
        <li>
          <div class="container-fluid">
            <div class="w3ls_banner_txt">
              <h3><span>Mude o Mundo</span>de Alguém</h3>
              <p class="w3ls_pvt-title">
                Ser voluntário é crescer a partir das experiência do outro.
              </p>
              <p class="w3ls_pvt-title mt-2">Experiências.</p>
              <a href="/cadastro" class="btn button-style mt-sm-5 mt-4">Inscreva-se</a>
            </div>
          </div>
        </li>
      </ul>
      <div class="navigation">
        <div>
          <label for="slides_1"></label>
          <label for="slides_2"></label>
          <label for="slides_3"></label>
        </div>
      </div>
    </div>
  </div>
  <!-- //banner -->

  <!-- //main banner -->

  <section class="conteudo" id="home">
    <h1>Sobre nós</h1>
    <!--/start-services-->
    <div class="Service-section">
      <div class="container">
        <div class="service-grids">
          <div class="col-md-4 service-grid">
            <h3>Nossa Missão</h3>
            <p>Na Colabora você vai trocar suas habilidades, por expêriencias reias.</p>
          </div>
          <div class="col-md-4 service-grid">
            <h3>Projetos</h3>
            <p>Publique seu projeto sem custo algum.
              Descreva o que você precisa, e receba pessoas capacitadas para te ajudar voluntariamente.
            </p>
          </div>
          <div class="col-md-4 service-grid">
            <h3>Experiência</h3>
            <p>Torne-se um mebro</p>
            <p>Voluntária-se para um projeto,<br>
              E garanta sua presença.
            </p>
          </div>
          <div class="clearfix"> </div>
        </div>
      </div>
    </div>
  </section>


  <section class="conteudo" id="equipe">

    <!--/start-stories-->
    <div class="Stories-section">

      <!--start-parts-->
      <div class="parts-section">
        <div class="container">
          <div class="ad728x90" style="text-align:center">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- w3layouts_demo_728x90 -->
            <ins class="adsbygoogle" style="display:inline-block;width:728px;height:90px" data-ad-client="ca-pub-9153409599391170" data-ad-slot="8639520288"></ins>
            <script>
              (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>



          <div class="gallery-head">
            <h3>A Equipe</h3>
          </div>
          <div class="section group">
            <div class="col-md-4 gallery-box">
              <div id="nivo-lightbox-demo">
                <p> <a href="images/pop1.png" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
                    <span class="rollover1"> </span></a>
                </p>
              </div>
              <img src="icons/avatar.png" alt="imagem Adriana">
              <div class="para_s">
                <h4>Adriana Diniz</h4>
                <p>Estudante na Universidade Senac
                  curso de TSI
                </p>
              </div>
            </div>
            <div class="col-md-4 gallery-box">
              <div id="nivo-lightbox-demo">
                <p> <a href="images/pop2.png" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
                    <span class="rollover1"> </span></a>
                </p>
              </div>
              <img src="icons/avatar.png" alt="imagem ALexandre">
              <div class="para_s">
                <h4>Alexandre</h4>
                <p>Estudante na Universidade Senac
                  curso de TSI</p>
              </div>
            </div>
            <div class="col-md-4 gallery-box">
              <div id="nivo-lightbox-demo">
                <p> <a href="images/pop3.png" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
                    <span class="rollover1"> </span></a>
                </p>
              </div>
              <img src="icons/avatar.png" alt="imagem Anna">
              <div class="para_s">
                <h4>Anna Barbara</h4>
                <p>Estudante na Universidade Senac
                  curso de TSI</p>
              </div>
            </div>
            <div class="clearfix"> </div>
          </div>
          <div class="section group">
            <div class="col-md-4 gallery-box">
              <div id="nivo-lightbox-demo">
                <p> <a href="images/pop4.png" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
                    <span class="rollover1"> </span></a>
                </p>
              </div>
              <img src="icons/avatar.png" alt="imagem Clayton">
              <div class="para_s">
                <h4>Clayton</h4>
                <p>Estudante na Universidade Senac
                  curso de TSI</p>
              </div>
            </div>
            <div class="col-md-4 gallery-box">
              <div id="nivo-lightbox-demo">
                <p> <a href="images/pop5.png" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
                    <span class="rollover1"> </span></a>
                </p>
              </div>
              <img src="icons/avatar.png" alt="Jorsias">
              <div class="para_s">
                <h4>Jorsias </h4>
                <p>Estudante na Universidade Senac
                  curso de TSI</p>
              </div>
            </div>
            <div class="col-md-4 gallery-box">
              <div id="nivo-lightbox-demo">
                <p> <a href="images/pop6.png" data-lightbox-gallery="gallery1" id="nivo-lightbox-demo">
                    <span class="rollover1"> </span></a>
                </p>
              </div>
              <img src="icons/avatar.png" alt="Tatiana">
              <div class="para_s">
                <h4>Tatiana</h4>
                <p>Estudante na Universidade Senac
                  curso de TSI</p>
              </div>
            </div>
            <div class="clearfix"> </div>
          </div>
          <script type="text/javascript" src="js/nivo-lightbox.min.js"></script>
          <script type="text/javascript">
            $(document).ready(function() {
              $('#nivo-lightbox-demo a').nivoLightbox({
                effect: 'fade'
              });
            });
          </script>
        </div>
      </div>

  </section>

  <footer class="footer">
    <div class='container-fluid footer__bottom'>
      <div>
        <div class='col-lg-6 col-md-6 col-sm-6'>
          <div class='fb_like_holder hidden-xs'>
            <div class='fb-like' colorscheme='dark' data-action='like' data-href='http://www.facebook.com/worldpackers' data-layout='standard' data-share='true' data-show-faces='true'></div>
          </div>
        </div>
        <div class='col-lg-6 col-md-6 col-sm-6'>
          <p>
            <a href="mailto:support@worldpackers.com">support@colabora.com.br</a>
            ou
            <strong>+55 11 4222191</strong>
          </p>
          <p class='small'>
            © 2019 Colabora • Rua das Fiandeiras - 500. Vila Olímpia, SP 04545005.
          </p>
          <div class="copy-right-grids">

            <div class="copy-right">
              <ul>
                <li><a href="#">Informações Colabora</a></li>
                <li><a href="#">Politica de Privacidade</a></li>
                <li><a href="#">Termos de Uso</a></li>
              </ul>
            </div>
            <div class="clear"></div>
          </div>
        </div>
      </div>
  </footer>

  <script type="text/javascript">
    $(document).ready(function() {
      $().UItoTop({
        easingType: 'easeOutQuart'
      });

    });
  </script>
  <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>




</body>

</html>