<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home Projetos</title>
</head>

<body>
    <header class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>
        <nav class="nav-collapse">
            <ul>
                <li class="menu-item"><a href="/index#home">Sobre nós</a></li>
                <li class="menu-item"><a href="/index#equipe">Equipe</a></li>
                <li class="menu-item"><a href="/index_projeto">Projetos</a></li>
                <li class="menu-item"><a href="/login">Entrar</a></li>
                <li class="menu-item"><a href="/cadastro">Registre-se</a></li>

            </ul>
        </nav>
    </header>
    <div class="clearfix"> </div>

    <?php foreach ($this->view->projetos as $id_projeto => $projeto) { ?>
        <div class="application_container container-fluid" id="home-projeto">
            <div class="row">
                <div class="col-md-8 col-lg-8 col-sm-10 col-md-offset-2 col-lg-offset-2 col-sm-offset-1">
                    <form class="box" id="user_about_info" action="#" method="POST">
                        <h1 class="mg_bot_40 "><?= $projeto['nome_projeto'] ?></h1>
                        <div class='box_content'>

                            <div class="expander" data-text-expand="Ver mais detalhes" data-text-collapse="colapsar" data-slice-point="300" inline-expander="true" data-text-prefix="...">
                                <?= $projeto['descricao'] ?>
                            </div>
                            <br><br>
                            <strong>Categoria:</strong>
                            <?= $projeto['nome_categoria'] ?>
                            <br><br>
                            <strong>Data:</strong>
                            <?= $projeto['data'] ?>

                        </div>
                        <br>
                        <div class='box_actions'>
                            <input type="submit" name="commit" value="Voluntariar-se" class="btn btn_lg btn_primary" />
                        </div>
                    </form>
                </div>
            </div>

        </div>
    <?php } ?>

    <footer class="footer">
        <div class='container-fluid footer__bottom'>
            <div>
                <div class='col-lg-6 col-md-6 col-sm-6'>
                    <div class='fb_like_holder hidden-xs'>
                        <div class='fb-like' colorscheme='dark' data-action='like' data-href='http://www.facebook.com/worldpackers' data-layout='standard' data-share='true' data-show-faces='true'></div>
                    </div>
                </div>
                <div class='col-lg-6 col-md-6 col-sm-6'>
                    <p>
                        <a href="mailto:support@worldpackers.com">support@colabora.com.br</a>
                        ou
                        <strong>+55 11 4222191</strong>
                    </p>
                    <p class='small'>
                        © 2019 Colabora • Rua das Fiandeiras - 500. Vila Olímpia, SP 04545005.
                    </p>
                    <div class="copy-right-grids">

                        <div class="copy-right">
                            <ul>
                                <li><a href="#">Informações Colabora</a></li>
                                <li><a href="#">Politica de Privacidade</a></li>
                                <li><a href="#">Termos de Uso</a></li>
                            </ul>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
    </footer>

    <script type="text/javascript">
        $(document).ready(function() {
            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

</body>

</html>