<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Interesses</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="index.html" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <nav class="nav-collapse">
                <a href="projeto.html" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Publicar um projeto</a>
            </nav>
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/profile3.jpg" alt="imagem perfil"> </span>
                            <div class="user-name">
                                <p>Anna Barbara</p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="/projeto"><i class="fa fa-edit"></i>Publicar Projeto</a> </li>
                        <li> <a href="/cadastro_editar"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="/perfil"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="/logoff"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>

    <div class="application_container container-fluid">
        <h1>Bora começar, Anna ?</h1>
        <div class="application_container container-fluid">
            <form class="onboarding-preferences__form" id="new_user_preferences" action="/index">
                <h1 class="text_center">Quais seus Interesses</h1>
                <p class="huge text_center">Selecione somente até três opções</p>
                <div class="row tam">
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_cidadania" class="checkbox_image cidadania" type="checkbox" value="cidadania" name="user_preferences[cidadania][]" />
                            <label for="habilidade_cidadania">
                                <div class='content'>
                                    <h4>Cidadania</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--fim-->
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_comunicacao" class="checkbox_image comunicacao" type="checkbox" value="comunicacao" name="user_preferences[comunicacao][]" />
                            <label for="habilidade_comunicacao">
                                <div class='content'>
                                    <h4>Educação</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--Fim-->
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_cozinha" class="checkbox_image cozinha" type="checkbox" value="cozinha" name="user_preferences[cozinha][]" />
                            <label for="habilidade_cozinha">
                                <div class='content'>
                                    <h4>Esporte</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--Fim-->
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_ensinar" class="checkbox_image ensinar" type="checkbox" value="ensinar" name="user_preferences[cidadania][]" />
                            <label for="habilidade_ensinar">
                                <div class='content'>
                                    <h4>Saúde</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--Fim-->
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_web" class="checkbox_image web" type="checkbox" value="web" name="user_preferences[web][]" />
                            <label for="habilidade_web">
                                <div class='content'>
                                    <h4>Cultura</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--Fim-->
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_reformas" class="checkbox_image reformas" type="checkbox" value="reformas" name="user_preferences[reformas][]" />
                            <label for="habilidade_reformas">
                                <div class='content'>
                                    <h4>Acão Social</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--Fim-->
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_decoracao" class="checkbox_image decoracao" type="checkbox" value="decoracao" name="user_preferences[decoracao][]" />
                            <label for="habilidade_decoracao">
                                <div class='content'>
                                    <h4>idiomas</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--Fim-->
                    <!--Interesses-->
                    <div class='col-md-4 col-lg-4'>
                        <div class='skill_option'>
                            <input id="habilidade_outros" class="checkbox_image outros" type="checkbox" value="outros" name="user_preferences[outros][]" />
                            <label for="habilidade_outros">
                                <div class='content'>
                                    <h4>Outros</h4>
                                </div>
                            </label>
                        </div>
                    </div>
                    <!--Fim-->

                </div>
        </div>

        <div class='box_actions_outros_i'>
            <input type="submit" name="commit" value="Proseguir" class="btn btn_lg btn_primary" id="enviar" />
        </div>

        </form>
    </div>
    </div>

</body>

</html>