<!DOCTYPE html>
<html>

<head>
    <title>Interesses</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="css/styles.css" rel='stylesheet' type='text/css' media="all">
    <script src="js/responsive-nav.js"></script>
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    <script src="js/jquery-2.1.4.min.js"></script>
</head>

<body>
    <!--header start here-->
    <div class="header-main">
        <a href="index.html" class="logo" data-scroll><b>C</b>olabora</a>

        <div class="w3layouts-right">
            <div class="profile_details_left">
                <!--notifications of menu start -->
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i
                                class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li><a href="#">
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a></li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="profile_details w3l">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="icons/in4.jpg" alt=""> </span>
                            <div class="user-name">
                                <p>Anna Barbara</p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down"></i>
                            <i class="fa fa-angle-up"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="cadastro_editar.html"><i class="fa fa-cog"></i>Conta</a> </li>
                        <li> <a href="#"><i class="fa fa-user"></i>Perfil</a> </li>
                        <li> <a href="#"><i class="fa fa-sign-out"></i>Sair</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>

    <div class="application_container container-fluid">
        <div class='onboarding-preferences'>
            <h1>Bora começar, Anna ?</h1>
            <h2 class="text huge mg_bot_40">Selecione as opções que mais tem a ver com você.</h2>
            <form class="onboarding-preferences__form" id="new_user_preferences" action="#">
                <h3 class="mg_bot_20">Quais são seus interesses?</h3>

                <div class="small-row">
                    <div class="small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6">
                        <input id="interesse_cidadania" class="checkbox_image cidadania" type="checkbox"
                            value="cidadania" name="user_preferences[cidadania][]" />
                        <label for="interesse_cidadania">
                            <div class='content'>
                                <h4>Cidadania</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="interesse_educacao" class="checkbox_image educacao" type="checkbox" value="educacao"
                            name="user_preferences[educacao][]" />
                        <label for="interesse_educacao">
                            <div class='content'>
                                <h4>Educação</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="interesse_esporte" class="checkbox_image esporte" type="checkbox" value="esporte"
                            name="user_preferences[esporte][]" />
                        <label for="interesse_esporte">
                            <div class='content'>
                                <h4>Esporte</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="interesse_saude" class="checkbox_image saude" type="checkbox" value="saude"
                            name="user_preferences[saude][]" />
                        <label for="interesse_saude">
                            <div class='content'>
                                <h4>Saúde</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="interesse_cultura" class="checkbox_image cultura" type="checkbox"
                            value="english_practice" name="user_preferences[cultura][]" />
                        <label for="interesse_cultura">
                            <div class='content'>
                                <h4>Cultura</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="acao_social" class="checkbox_image social" type="checkbox" value="english_practice"
                            name="user_preferences[acao_social][]" />
                        <label for="acao_social">
                            <div class='content'>
                                <h4>Ação Social</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="praticar_ingles" class="checkbox_image ingles" type="checkbox"
                            value="english_practice" name="user_preferences[ingles][]" />
                        <label for="praticar_ingles">
                            <div class='content'>
                                <h4>Práticar Inglês</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="outros" class="checkbox_image outros" type="checkbox" value="outros"
                            name="user_preferences[outros][]" />
                        <label for="outros">
                            <div class='content'>
                                <h4>Outros</h4>
                            </div>
                        </label></div>

                    <h3 class="mg_bot_20">Como pretende ajudar?</h3>

                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_administrativo" class="checkbox_image administrativo" type="checkbox"
                            value="administrativo" name="user_preferences[administrativo][]" />
                        <label for="ajuda_administrativo">
                            <div class='content'>
                                <h4>Rotinas Administrativas</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_comunicacao" class="checkbox_image comunicacao" type="checkbox"
                            value="comunicacao" name="user_preferences[comunicacao][]" />
                        <label for="ajuda_comunicacao">
                            <div class='content'>
                                <h4>Comunicação e Marketing</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_cozinha" class="checkbox_image cozinha" type="checkbox" value="cozinha"
                            name="user_preferences[cozinha][]" />
                        <label for="ajuda_cozinha">
                            <div class='content'>
                                <h4>Cozinha</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_ensinar" class="checkbox_image ensinar" type="checkbox" value="ensinar"
                            name="user_preferences[ensinar][]" />
                        <label for="ajuda_ensinar">
                            <div class='content'>
                                <h4>Ensinar e Compartilhar</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_web" class="checkbox_image web" type="checkbox" value="web"
                            name="user_preferences[web][]" />
                        <label for="ajuda_web">
                            <div class='content'>
                                <h4>Desenvolvimento Web</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_reformas" class="checkbox_image reformas" type="checkbox" value="reformas"
                            name="user_preferences[reformas][]" />
                        <label for="ajuda_reformas">
                            <div class='content'>
                                <h4>Reformas</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_decoracao" class="checkbox_image decoracao" type="checkbox"
                            value="administrativo" name="user_preferences[decoracao][]" />
                        <label for="ajuda_decoracao">
                            <div class='content'>
                                <h4>Decoração</h4>
                            </div>
                        </label></div>
                    <div class='small-col-lg-3 small-col-md-3 small-col-sm-4 small-col-xs-6'>
                        <input id="ajuda_comunitario" class="checkbox_image comunitario" type="checkbox"
                            value="administrativo" name="user_preferences[comunicario][]" />
                        <label for="ajuda_comunitario">
                            <div class='content'>
                                <h4>Trabalho Comunitário</h4>
                            </div>
                        </label></div>

                        <input type="submit" value="Prosseguir" class="btn btn_huge btn_shadow  btn_primary"  />
                        </div>

                </div>
                <!---->button name="button" class="btn btn_huge btn_shadow btn_primary" type="submit"
                    id="submit-preferences">Prosseguir<!---->/button>
            </form>
        </div>

        <script src="js/fastclick.js"></script>
        <script src="js/scroll.js"></script>
        <script src="js/fixed-responsive-nav.js"></script>
        <script src="js/bootstrap.min.js"></script>

</body>

</html>