<?php session_start(); ?>
<!DOCTYPE html>
<html lang='pt-BR'>

<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
    <header class="header-main">
        <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>
        <nav class="nav-collapse">
            <ul>
                <li class="menu-item"><a href="/index#home">Sobre nós</a></li>
                <li class="menu-item"><a href="/index#equipe">Equipe</a></li>
                <li class="menu-item"><a href="/index_projeto">Projetos</a></li>
                <li class="menu-item"><a href="/login">Entrar</a></li>
                <li class="menu-item"><a href="/cadastro">Registre-se</a></li>

            </ul>
        </nav>
    </header>
    <section class="registration">
        <div class="container-fluid">
            <div class="box registration_box">
                <h1 class="h2 text_center">Entrar</h1>
                <form class="new_user" id="new_user" action="/autenticar" method="POST">
                    <div class="form-group">
                        <input autofocus="autofocus" type="email" value="" class="form_input email_input" id="user_email" placeholder="E-mail" name="email" required>
                        <div class="invalid-feedback">
                            Please choose a username.
                        </div>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" type="password" class="form_input password_input" value="" id="pwd" placeholder="Sua senha" name="senha" required>
                    </div>
                    <div class="forgot_password_holder">
                        <a class="small" href="#">Deu branco na senha?</a>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Entrar" class="btn btn_primary btn_block" />
                    </div>

            </div>

            <?php if ($this->view->auth == 'erro') { ?>
                <div class="alert alert-danger" role="alert">Entre com um email e senha válidos ou cadastre-se</div>
            <?php } ?>
            </form>
        </div>
        <h2 class="h4 pt-5 with_link text-center">
            Não é membro ainda?
            <br>
            <a href="/cadastro">Cadastre-se</a>
        </h2>
    </section>

    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
            'use strict';
            window.addEventListener('load', function() {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName("new_user");
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
</body>

</html>