<!DOCTYPE html>
<html>

<head>
  <title>Projeto</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
</head>
</head>

<body>
  <?php
  /*$lista = $this->view->ListarProjetos();
      foreach ($lista as $key => $value) {
        echo $value."</br>";
      }*/
  ?>

  <!--header start here-->
  <div class="header-main">
    <a href="/index" class="logo" data-scroll><b>C</b>olabora</a>
    
    <div class="clearfix"> </div>
  </div>

  <div class="application_container">
    <div class="container-fluid">
      <h1 class="h2 text_center">Publique seu projeto!</h1>
      <div class="box box_pro">
        <form class="register_form inactive" id="new_user" action="#" method="POST">
          <div class="form-group">
            <label for="user_catego">Selecione Categoria</label>
            <select class="form_input gender_input" name="user_gender" id="user_catego">
              <option value="">Categoria</option>
              <option value="F">Programação</option>
              <option value="M">Programação</option>
              <option value="N">Programação</option>
            </select>
          </div>
          <div class="form-group">
            <label for="user_projeto">Nome Projeto</label>
            <input placeholder="Nome do Projeto" type="text" class="form_input name_input" id="user_projeto" name="nome_projeto">
          </div>
          <div class="form-group">
            <label for="comment">Descreva o trabalho a ser realizado</label>
            <textarea class="form-control" rows="10" id="comment" placeholder="iclua aqui todos os detalhes que puder, incluind informações de contato (e-amil, telefone, nome)"></textarea>
          </div>

          <input type="submit" name="comit" value="Publica Projeto" class="btn btn_lg btn_primary btn_block">
        </form>
      </div>

    </div>

  </div>


 


</body>

</html>